// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cose$0 from "../cose/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as credential$0 from "../credential/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as extension$0 from "../extension/models.js";

export class AuthenticationExtensionsLargeBlobInputs {
    "support"?: extension$0.LargeBlobSupport;
    "read"?: boolean | null;
    "write"?: string;

    /** Creates a new AuthenticationExtensionsLargeBlobInputs instance. */
    constructor($$source: Partial<AuthenticationExtensionsLargeBlobInputs> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthenticationExtensionsLargeBlobInputs instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthenticationExtensionsLargeBlobInputs {
        const $$createField2_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("write" in $$parsedSource) {
            $$parsedSource["write"] = $$createField2_0($$parsedSource["write"]);
        }
        return new AuthenticationExtensionsLargeBlobInputs($$parsedSource as Partial<AuthenticationExtensionsLargeBlobInputs>);
    }
}

export class AuthenticationExtensionsPRFInputs {
    "eval"?: AuthenticationExtensionsPRFValues;
    "evalByCredential"?: { [_ in string]?: AuthenticationExtensionsPRFValues };

    /** Creates a new AuthenticationExtensionsPRFInputs instance. */
    constructor($$source: Partial<AuthenticationExtensionsPRFInputs> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthenticationExtensionsPRFInputs instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthenticationExtensionsPRFInputs {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("eval" in $$parsedSource) {
            $$parsedSource["eval"] = $$createField0_0($$parsedSource["eval"]);
        }
        if ("evalByCredential" in $$parsedSource) {
            $$parsedSource["evalByCredential"] = $$createField1_0($$parsedSource["evalByCredential"]);
        }
        return new AuthenticationExtensionsPRFInputs($$parsedSource as Partial<AuthenticationExtensionsPRFInputs>);
    }
}

export class AuthenticationExtensionsPRFValues {
    "first": string;
    "second"?: string;

    /** Creates a new AuthenticationExtensionsPRFValues instance. */
    constructor($$source: Partial<AuthenticationExtensionsPRFValues> = {}) {
        if (!("first" in $$source)) {
            this["first"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthenticationExtensionsPRFValues instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthenticationExtensionsPRFValues {
        const $$createField0_0 = $Create.ByteSlice;
        const $$createField1_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("first" in $$parsedSource) {
            $$parsedSource["first"] = $$createField0_0($$parsedSource["first"]);
        }
        if ("second" in $$parsedSource) {
            $$parsedSource["second"] = $$createField1_0($$parsedSource["second"]);
        }
        return new AuthenticationExtensionsPRFValues($$parsedSource as Partial<AuthenticationExtensionsPRFValues>);
    }
}

export class AuthenticationExtensionsPaymentInputs {
    "payment": boolean;
    "browserBoundPubKeyCredParams": credential$0.PublicKeyCredentialParameters[];
    "rpId": string;
    "topOrigin": string;
    "payeeName": string;
    "payeeOrigin": string;
    "paymentEntitiesLogos": PaymentEntityLogo[];
    "total": PaymentCurrencyAmount | null;
    "instrument": PaymentCredentialInstrument | null;

    /** Creates a new AuthenticationExtensionsPaymentInputs instance. */
    constructor($$source: Partial<AuthenticationExtensionsPaymentInputs> = {}) {
        if (!("payment" in $$source)) {
            this["payment"] = false;
        }
        if (!("browserBoundPubKeyCredParams" in $$source)) {
            this["browserBoundPubKeyCredParams"] = [];
        }
        if (!("rpId" in $$source)) {
            this["rpId"] = "";
        }
        if (!("topOrigin" in $$source)) {
            this["topOrigin"] = "";
        }
        if (!("payeeName" in $$source)) {
            this["payeeName"] = "";
        }
        if (!("payeeOrigin" in $$source)) {
            this["payeeOrigin"] = "";
        }
        if (!("paymentEntitiesLogos" in $$source)) {
            this["paymentEntitiesLogos"] = [];
        }
        if (!("total" in $$source)) {
            this["total"] = null;
        }
        if (!("instrument" in $$source)) {
            this["instrument"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthenticationExtensionsPaymentInputs instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthenticationExtensionsPaymentInputs {
        const $$createField1_0 = $$createType3;
        const $$createField6_0 = $$createType5;
        const $$createField7_0 = $$createType7;
        const $$createField8_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("browserBoundPubKeyCredParams" in $$parsedSource) {
            $$parsedSource["browserBoundPubKeyCredParams"] = $$createField1_0($$parsedSource["browserBoundPubKeyCredParams"]);
        }
        if ("paymentEntitiesLogos" in $$parsedSource) {
            $$parsedSource["paymentEntitiesLogos"] = $$createField6_0($$parsedSource["paymentEntitiesLogos"]);
        }
        if ("total" in $$parsedSource) {
            $$parsedSource["total"] = $$createField7_0($$parsedSource["total"]);
        }
        if ("instrument" in $$parsedSource) {
            $$parsedSource["instrument"] = $$createField8_0($$parsedSource["instrument"]);
        }
        return new AuthenticationExtensionsPaymentInputs($$parsedSource as Partial<AuthenticationExtensionsPaymentInputs>);
    }
}

export class AuthenticationExtensionsPreviewSignInputs {
    "generateKey"?: PreviewSignGenerateKeyInputs | null;
    "signByCredential"?: { [_ in string]?: PreviewSignSignInputs };

    /** Creates a new AuthenticationExtensionsPreviewSignInputs instance. */
    constructor($$source: Partial<AuthenticationExtensionsPreviewSignInputs> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthenticationExtensionsPreviewSignInputs instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthenticationExtensionsPreviewSignInputs {
        const $$createField0_0 = $$createType11;
        const $$createField1_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("generateKey" in $$parsedSource) {
            $$parsedSource["generateKey"] = $$createField0_0($$parsedSource["generateKey"]);
        }
        if ("signByCredential" in $$parsedSource) {
            $$parsedSource["signByCredential"] = $$createField1_0($$parsedSource["signByCredential"]);
        }
        return new AuthenticationExtensionsPreviewSignInputs($$parsedSource as Partial<AuthenticationExtensionsPreviewSignInputs>);
    }
}

export class CreateAuthenticationExtensionsClientInputs {
    "credBlob"?: string;
    "credProps"?: boolean;
    "credentialProtectionPolicy"?: extension$0.CredentialProtectionPolicy;
    "enforceCredentialProtectionPolicy"?: boolean;
    "hmacCreateSecret"?: boolean;
    "hmacGetSecret"?: HMACGetSecretInput;
    "largeBlob"?: AuthenticationExtensionsLargeBlobInputs;
    "minPinLength"?: boolean;
    "pinComplexityPolicy"?: boolean;
    "payment"?: AuthenticationExtensionsPaymentInputs;
    "prf"?: AuthenticationExtensionsPRFInputs;
    "previewSign": AuthenticationExtensionsPreviewSignInputs;

    /** Creates a new CreateAuthenticationExtensionsClientInputs instance. */
    constructor($$source: Partial<CreateAuthenticationExtensionsClientInputs> = {}) {
        if (!("previewSign" in $$source)) {
            this["previewSign"] = (new AuthenticationExtensionsPreviewSignInputs());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateAuthenticationExtensionsClientInputs instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateAuthenticationExtensionsClientInputs {
        const $$createField0_0 = $Create.ByteSlice;
        const $$createField5_0 = $$createType14;
        const $$createField6_0 = $$createType15;
        const $$createField9_0 = $$createType16;
        const $$createField10_0 = $$createType17;
        const $$createField11_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("credBlob" in $$parsedSource) {
            $$parsedSource["credBlob"] = $$createField0_0($$parsedSource["credBlob"]);
        }
        if ("hmacGetSecret" in $$parsedSource) {
            $$parsedSource["hmacGetSecret"] = $$createField5_0($$parsedSource["hmacGetSecret"]);
        }
        if ("largeBlob" in $$parsedSource) {
            $$parsedSource["largeBlob"] = $$createField6_0($$parsedSource["largeBlob"]);
        }
        if ("payment" in $$parsedSource) {
            $$parsedSource["payment"] = $$createField9_0($$parsedSource["payment"]);
        }
        if ("prf" in $$parsedSource) {
            $$parsedSource["prf"] = $$createField10_0($$parsedSource["prf"]);
        }
        if ("previewSign" in $$parsedSource) {
            $$parsedSource["previewSign"] = $$createField11_0($$parsedSource["previewSign"]);
        }
        return new CreateAuthenticationExtensionsClientInputs($$parsedSource as Partial<CreateAuthenticationExtensionsClientInputs>);
    }
}

export class CredentialPropertiesOutput {
    "rk"?: boolean | null;

    /** Creates a new CredentialPropertiesOutput instance. */
    constructor($$source: Partial<CredentialPropertiesOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialPropertiesOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialPropertiesOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialPropertiesOutput($$parsedSource as Partial<CredentialPropertiesOutput>);
    }
}

export class GetAuthenticationExtensionsClientInputs {
    "getCredBlob"?: boolean;
    "hmacGetSecret"?: HMACGetSecretInput;
    "largeBlob"?: AuthenticationExtensionsLargeBlobInputs;
    "payment"?: AuthenticationExtensionsPaymentInputs;
    "prf"?: AuthenticationExtensionsPRFInputs;
    "previewSign": AuthenticationExtensionsPreviewSignInputs;

    /** Creates a new GetAuthenticationExtensionsClientInputs instance. */
    constructor($$source: Partial<GetAuthenticationExtensionsClientInputs> = {}) {
        if (!("previewSign" in $$source)) {
            this["previewSign"] = (new AuthenticationExtensionsPreviewSignInputs());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAuthenticationExtensionsClientInputs instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAuthenticationExtensionsClientInputs {
        const $$createField1_0 = $$createType14;
        const $$createField2_0 = $$createType15;
        const $$createField3_0 = $$createType16;
        const $$createField4_0 = $$createType17;
        const $$createField5_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hmacGetSecret" in $$parsedSource) {
            $$parsedSource["hmacGetSecret"] = $$createField1_0($$parsedSource["hmacGetSecret"]);
        }
        if ("largeBlob" in $$parsedSource) {
            $$parsedSource["largeBlob"] = $$createField2_0($$parsedSource["largeBlob"]);
        }
        if ("payment" in $$parsedSource) {
            $$parsedSource["payment"] = $$createField3_0($$parsedSource["payment"]);
        }
        if ("prf" in $$parsedSource) {
            $$parsedSource["prf"] = $$createField4_0($$parsedSource["prf"]);
        }
        if ("previewSign" in $$parsedSource) {
            $$parsedSource["previewSign"] = $$createField5_0($$parsedSource["previewSign"]);
        }
        return new GetAuthenticationExtensionsClientInputs($$parsedSource as Partial<GetAuthenticationExtensionsClientInputs>);
    }
}

export class HMACGetSecretInput {
    "salt1": string;
    "salt2"?: string;

    /** Creates a new HMACGetSecretInput instance. */
    constructor($$source: Partial<HMACGetSecretInput> = {}) {
        if (!("salt1" in $$source)) {
            this["salt1"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HMACGetSecretInput instance from a string or object.
     */
    static createFrom($$source: any = {}): HMACGetSecretInput {
        const $$createField0_0 = $Create.ByteSlice;
        const $$createField1_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("salt1" in $$parsedSource) {
            $$parsedSource["salt1"] = $$createField0_0($$parsedSource["salt1"]);
        }
        if ("salt2" in $$parsedSource) {
            $$parsedSource["salt2"] = $$createField1_0($$parsedSource["salt2"]);
        }
        return new HMACGetSecretInput($$parsedSource as Partial<HMACGetSecretInput>);
    }
}

export class PaymentCredentialInstrument {
    "displayName": string;
    "icon": string;

    /**
     * should default to true
     */
    "iconMustBeShown"?: string;
    "details"?: string;

    /** Creates a new PaymentCredentialInstrument instance. */
    constructor($$source: Partial<PaymentCredentialInstrument> = {}) {
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaymentCredentialInstrument instance from a string or object.
     */
    static createFrom($$source: any = {}): PaymentCredentialInstrument {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PaymentCredentialInstrument($$parsedSource as Partial<PaymentCredentialInstrument>);
    }
}

export class PaymentCurrencyAmount {
    "currency": string;
    "value": string;

    /** Creates a new PaymentCurrencyAmount instance. */
    constructor($$source: Partial<PaymentCurrencyAmount> = {}) {
        if (!("currency" in $$source)) {
            this["currency"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaymentCurrencyAmount instance from a string or object.
     */
    static createFrom($$source: any = {}): PaymentCurrencyAmount {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PaymentCurrencyAmount($$parsedSource as Partial<PaymentCurrencyAmount>);
    }
}

export class PaymentEntityLogo {
    "url": string;
    "label": string;

    /** Creates a new PaymentEntityLogo instance. */
    constructor($$source: Partial<PaymentEntityLogo> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PaymentEntityLogo instance from a string or object.
     */
    static createFrom($$source: any = {}): PaymentEntityLogo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PaymentEntityLogo($$parsedSource as Partial<PaymentEntityLogo>);
    }
}

export class PreviewSignGenerateKeyInputs {
    "algorithms": cose$0.Algorithm[];

    /** Creates a new PreviewSignGenerateKeyInputs instance. */
    constructor($$source: Partial<PreviewSignGenerateKeyInputs> = {}) {
        if (!("algorithms" in $$source)) {
            this["algorithms"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewSignGenerateKeyInputs instance from a string or object.
     */
    static createFrom($$source: any = {}): PreviewSignGenerateKeyInputs {
        const $$createField0_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("algorithms" in $$parsedSource) {
            $$parsedSource["algorithms"] = $$createField0_0($$parsedSource["algorithms"]);
        }
        return new PreviewSignGenerateKeyInputs($$parsedSource as Partial<PreviewSignGenerateKeyInputs>);
    }
}

export class PreviewSignSignInputs {
    "keyHandle": string;
    "tbs": string;
    "additionalArgs"?: string;

    /** Creates a new PreviewSignSignInputs instance. */
    constructor($$source: Partial<PreviewSignSignInputs> = {}) {
        if (!("keyHandle" in $$source)) {
            this["keyHandle"] = "";
        }
        if (!("tbs" in $$source)) {
            this["tbs"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewSignSignInputs instance from a string or object.
     */
    static createFrom($$source: any = {}): PreviewSignSignInputs {
        const $$createField0_0 = $Create.ByteSlice;
        const $$createField1_0 = $Create.ByteSlice;
        const $$createField2_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keyHandle" in $$parsedSource) {
            $$parsedSource["keyHandle"] = $$createField0_0($$parsedSource["keyHandle"]);
        }
        if ("tbs" in $$parsedSource) {
            $$parsedSource["tbs"] = $$createField1_0($$parsedSource["tbs"]);
        }
        if ("additionalArgs" in $$parsedSource) {
            $$parsedSource["additionalArgs"] = $$createField2_0($$parsedSource["additionalArgs"]);
        }
        return new PreviewSignSignInputs($$parsedSource as Partial<PreviewSignSignInputs>);
    }
}

// Private type creation functions
const $$createType0 = AuthenticationExtensionsPRFValues.createFrom;
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = credential$0.PublicKeyCredentialParameters.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = PaymentEntityLogo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = PaymentCurrencyAmount.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = PaymentCredentialInstrument.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = PreviewSignGenerateKeyInputs.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = PreviewSignSignInputs.createFrom;
const $$createType13 = $Create.Map($Create.Any, $$createType12);
const $$createType14 = HMACGetSecretInput.createFrom;
const $$createType15 = AuthenticationExtensionsLargeBlobInputs.createFrom;
const $$createType16 = AuthenticationExtensionsPaymentInputs.createFrom;
const $$createType17 = AuthenticationExtensionsPRFInputs.createFrom;
const $$createType18 = AuthenticationExtensionsPreviewSignInputs.createFrom;
const $$createType19 = $Create.Array($Create.Any);
