// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uuid$0 from "../../../../google/uuid/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as attestation$0 from "../../../ctap/attestation/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as credential$0 from "../../../ctap/credential/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as extension$0 from "../../../ctap/extension/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as protocol$0 from "../../../ctap/protocol/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as report$0 from "../report/models.js";

/**
 * Assessment is the deterministic, presentation-neutral interpretation of an
 * authenticatorGetInfo response.
 */
export class Assessment {
    "facts": Fact[];

    /** Creates a new Assessment instance. */
    constructor($$source: Partial<Assessment> = {}) {
        if (!("facts" in $$source)) {
            this["facts"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Assessment instance from a string or object.
     */
    static createFrom($$source: any = {}): Assessment {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("facts" in $$parsedSource) {
            $$parsedSource["facts"] = $$createField0_0($$parsedSource["facts"]);
        }
        return new Assessment($$parsedSource as Partial<Assessment>);
    }
}

/**
 * Fact describes one stable GetInfo capability or observation.
 */
export class Fact {
    "id": FactID;
    "source": FactSource;
    "state": FactState;
    "origin": FactOrigin;
    "value": FactValue;

    /** Creates a new Fact instance. */
    constructor($$source: Partial<Fact> = {}) {
        if (!("id" in $$source)) {
            this["id"] = FactID.$zero;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = FactState.$zero;
        }
        if (!("origin" in $$source)) {
            this["origin"] = FactOrigin.$zero;
        }
        if (!("value" in $$source)) {
            this["value"] = (new FactValue());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Fact instance from a string or object.
     */
    static createFrom($$source: any = {}): Fact {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("value" in $$parsedSource) {
            $$parsedSource["value"] = $$createField4_0($$parsedSource["value"]);
        }
        return new Fact($$parsedSource as Partial<Fact>);
    }
}

export enum FactID {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FactIDAAGUID = "aaguid",
    FactIDTransports = "transports",
    FactIDPlatformAttachment = "platform_attachment",
    FactIDEncryptedDeviceIdentifier = "encrypted_device_identifier",
    FactIDVersions = "versions",
    FactIDVersionU2FV2 = "version_u2f_v2",
    FactIDVersionFIDO20 = "version_fido_2_0",
    FactIDVersionFIDO21Preview = "version_fido_2_1_pre",
    FactIDVersionFIDO21 = "version_fido_2_1",
    FactIDVersionFIDO23 = "version_fido_2_3",
    FactIDAlgorithms = "algorithms",
    FactIDUserPresence = "user_presence",
    FactIDResidentCredentials = "resident_credentials",
    FactIDClientPIN = "client_pin",
    FactIDUserVerification = "user_verification",
    FactIDPinUvAuthToken = "pin_uv_auth_token",
    FactIDClientPINMCGAPermissions = "client_pin_mc_ga_permissions",
    FactIDPinUvAuthProtocols = "pin_uv_auth_protocols",
    FactIDBioEnrollment = "bio_enrollment",
    FactIDBioEnrollmentPreview = "bio_enrollment_preview",
    FactIDUvBioEnroll = "uv_bio_enroll",
    FactIDUvModality = "uv_modality",
    FactIDPreferredPlatformUVAttempts = "preferred_platform_uv_attempts",
    FactIDUVCountSinceLastPINEntry = "uv_count_since_last_pin_entry",
    FactIDLargeBlobs = "large_blobs",
    FactIDLargeBlobKey = "large_blob_key",
    FactIDMaxSerializedLargeBlobArray = "max_serialized_large_blob_array",
    FactIDMaxCredBlobLength = "max_cred_blob_length",
    FactIDEncryptedCredentialStoreState = "encrypted_credential_store_state",
    FactIDCredentialManagement = "credential_management",
    FactIDCredentialManagementPreview = "credential_management_preview",
    FactIDCredentialManagementReadOnly = "credential_management_read_only",
    FactIDAuthenticatorConfig = "authenticator_config",
    FactIDUvAuthenticatorConfig = "uv_authenticator_config",
    FactIDAuthenticatorConfigCommands = "authenticator_config_commands",
    FactIDVendorPrototypeConfigCommands = "vendor_prototype_config_commands",
    FactIDLongTouchForReset = "long_touch_for_reset",
    FactIDTransportsForReset = "transports_for_reset",
    FactIDEnterpriseAttestation = "enterprise_attestation",
    FactIDAlwaysUV = "always_uv",
    FactIDSetMinPINLength = "set_min_pin_length",
    FactIDMakeCredentialUVRequirement = "make_credential_uv_requirement",
    FactIDForcePINChange = "force_pin_change",
    FactIDPINComplexityPolicy = "pin_complexity_policy",
    FactIDPINComplexityPolicyURL = "pin_complexity_policy_url",
    FactIDMaxRPIDsForSetMinPINLength = "max_rp_ids_for_set_min_pin_length",
    FactIDExtensionCredProtect = "extension_cred_protect",
    FactIDExtensionCredBlob = "extension_cred_blob",
    FactIDExtensionLargeBlobKey = "extension_large_blob_key",
    FactIDExtensionLargeBlob = "extension_large_blob",
    FactIDExtensionMinPINLength = "extension_min_pin_length",
    FactIDExtensionPINComplexityPolicy = "extension_pin_complexity_policy",
    FactIDExtensionHMACSecret = "extension_hmac_secret",
    FactIDExtensionHMACSecretMC = "extension_hmac_secret_mc",
    FactIDExtensionThirdPartyPayment = "extension_third_party_payment",
    FactIDExtensionPreviewSign = "extension_preview_sign",
    FactIDEffectiveMaxMessageSize = "effective_max_message_size",
    FactIDMaxCredentialCountInList = "max_credential_count_in_list",
    FactIDMaxCredentialIDLength = "max_credential_id_length",
    FactIDEffectiveMinPINLength = "effective_min_pin_length",
    FactIDEffectiveMaxPINLength = "effective_max_pin_length",
    FactIDRemainingDiscoverableCredentials = "remaining_discoverable_credentials",
    FactIDAttestationFormats = "attestation_formats",
    FactIDCertifications = "certifications",
    FactIDFirmwareVersion = "firmware_version",
};

export enum FactOrigin {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FactOriginReported = "reported",
    FactOriginSpecDefault = "spec_default",
    FactOriginDerived = "derived",
    FactOriginAbsent = "absent",
};

export type FactSource = string;

export enum FactState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FactStateObserved = "observed",
    FactStateUnknown = "unknown",
    FactStateSupported = "supported",
    FactStateUnsupported = "unsupported",
    FactStateConfigured = "configured",
    FactStateNotConfigured = "not_configured",
    FactStateEnabled = "enabled",
    FactStateDisabled = "disabled",
    FactStateRequired = "required",
    FactStateNotRequired = "not_required",
    FactStateWarning = "warning",
};

export enum FactUnit {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FactUnitBytes = "bytes",
    FactUnitCodePoints = "code_points",
};

/**
 * FactValue is a JSON-friendly tagged union. Exactly one value field is set
 * for observed, derived, or defaulted facts; unknown facts carry only Kind.
 */
export class FactValue {
    "kind": FactValueKind;
    "boolean"?: boolean | null;
    "integer"?: number | null;
    "text"?: string | null;
    "list"?: string[] | null;
    "unit"?: FactUnit;

    /** Creates a new FactValue instance. */
    constructor($$source: Partial<FactValue> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = FactValueKind.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FactValue instance from a string or object.
     */
    static createFrom($$source: any = {}): FactValue {
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("list" in $$parsedSource) {
            $$parsedSource["list"] = $$createField4_0($$parsedSource["list"]);
        }
        return new FactValue($$parsedSource as Partial<FactValue>);
    }
}

export enum FactValueKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FactValueBoolean = "boolean",
    FactValueInteger = "integer",
    FactValueText = "text",
    FactValueList = "list",
};

export class Info {
    "versions": protocol$0.Versions;
    "extensions"?: extension$0.ExtensionIdentifier[];
    "aaguid": uuid$0.UUID;
    "options"?: { [_ in protocol$0.Option]?: boolean };
    "maxMsgSize"?: number;
    "pinUvAuthProtocols"?: protocol$0.PinUvAuthProtocol[];
    "maxCredentialCountInList"?: number;
    "maxCredentialIdLength"?: number;
    "transports"?: credential$0.AuthenticatorTransport[];
    "algorithms"?: credential$0.PublicKeyCredentialParameters[];
    "maxSerializedLargeBlobArray"?: number;
    "forcePINChange"?: boolean;
    "minPINLength"?: number;
    "firmwareVersion"?: number | null;
    "maxCredBlobLength"?: number;
    "maxRPIDsForSetMinPINLength"?: number | null;
    "preferredPlatformUvAttempts"?: number;
    "uvModality"?: protocol$0.UserVerify | null;
    "certifications"?: { [_ in string]?: number };
    "remainingDiscoverableCredentials"?: number | null;
    "vendorPrototypeConfigCommands"?: protocol$0.VendorCommandID[];
    "attestationFormats"?: attestation$0.AttestationStatementFormatIdentifier[];
    "uvCountSinceLastPinEntry"?: number | null;
    "longTouchForReset"?: boolean | null;
    "encIdentifier"?: string;
    "transportsForReset"?: credential$0.AuthenticatorTransport[];
    "pinComplexityPolicy"?: boolean | null;
    "pinComplexityPolicyURL"?: string;
    "maxPINLength"?: number;
    "encCredStoreState"?: string;
    "authenticatorConfigCommands"?: protocol$0.ConfigSubCommand[];
    "uvModalityLabel"?: string;
    "assessment": Assessment;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("versions" in $$source)) {
            this["versions"] = [];
        }
        if (!("aaguid" in $$source)) {
            this["aaguid"] = "";
        }
        if (!("assessment" in $$source)) {
            this["assessment"] = (new Assessment());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType7;
        const $$createField3_0 = $$createType8;
        const $$createField5_0 = $$createType9;
        const $$createField8_0 = $$createType10;
        const $$createField9_0 = $$createType12;
        const $$createField18_0 = $$createType13;
        const $$createField20_0 = $$createType14;
        const $$createField21_0 = $$createType15;
        const $$createField24_0 = $Create.ByteSlice;
        const $$createField25_0 = $$createType10;
        const $$createField27_0 = $Create.ByteSlice;
        const $$createField29_0 = $Create.ByteSlice;
        const $$createField30_0 = $$createType16;
        const $$createField32_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField0_0($$parsedSource["versions"]);
        }
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField1_0($$parsedSource["extensions"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        if ("pinUvAuthProtocols" in $$parsedSource) {
            $$parsedSource["pinUvAuthProtocols"] = $$createField5_0($$parsedSource["pinUvAuthProtocols"]);
        }
        if ("transports" in $$parsedSource) {
            $$parsedSource["transports"] = $$createField8_0($$parsedSource["transports"]);
        }
        if ("algorithms" in $$parsedSource) {
            $$parsedSource["algorithms"] = $$createField9_0($$parsedSource["algorithms"]);
        }
        if ("certifications" in $$parsedSource) {
            $$parsedSource["certifications"] = $$createField18_0($$parsedSource["certifications"]);
        }
        if ("vendorPrototypeConfigCommands" in $$parsedSource) {
            $$parsedSource["vendorPrototypeConfigCommands"] = $$createField20_0($$parsedSource["vendorPrototypeConfigCommands"]);
        }
        if ("attestationFormats" in $$parsedSource) {
            $$parsedSource["attestationFormats"] = $$createField21_0($$parsedSource["attestationFormats"]);
        }
        if ("encIdentifier" in $$parsedSource) {
            $$parsedSource["encIdentifier"] = $$createField24_0($$parsedSource["encIdentifier"]);
        }
        if ("transportsForReset" in $$parsedSource) {
            $$parsedSource["transportsForReset"] = $$createField25_0($$parsedSource["transportsForReset"]);
        }
        if ("pinComplexityPolicyURL" in $$parsedSource) {
            $$parsedSource["pinComplexityPolicyURL"] = $$createField27_0($$parsedSource["pinComplexityPolicyURL"]);
        }
        if ("encCredStoreState" in $$parsedSource) {
            $$parsedSource["encCredStoreState"] = $$createField29_0($$parsedSource["encCredStoreState"]);
        }
        if ("authenticatorConfigCommands" in $$parsedSource) {
            $$parsedSource["authenticatorConfigCommands"] = $$createField30_0($$parsedSource["authenticatorConfigCommands"]);
        }
        if ("assessment" in $$parsedSource) {
            $$parsedSource["assessment"] = $$createField32_0($$parsedSource["assessment"]);
        }
        return new Info($$parsedSource as Partial<Info>);
    }
}

export class Result {
    "device": report$0.DeviceReport;
    "info": Info;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("device" in $$source)) {
            this["device"] = (new report$0.DeviceReport());
        }
        if (!("info" in $$source)) {
            this["info"] = (new Info());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField0_0 = $$createType18;
        const $$createField1_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("device" in $$parsedSource) {
            $$parsedSource["device"] = $$createField0_0($$parsedSource["device"]);
        }
        if ("info" in $$parsedSource) {
            $$parsedSource["info"] = $$createField1_0($$parsedSource["info"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

// Private type creation functions
const $$createType0 = Fact.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = FactValue.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Nullable($$createType3);
var $$createType5 = (function $$initCreateType5(...args: any[]): any {
    if ($$createType5 === $$initCreateType5) {
        $$createType5 = $$createType6;
    }
    return $$createType5(...args);
});
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = credential$0.PublicKeyCredentialParameters.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Map($Create.Any, $Create.Any);
const $$createType14 = $Create.Array($Create.Any);
const $$createType15 = $Create.Array($Create.Any);
const $$createType16 = $Create.Array($Create.Any);
const $$createType17 = Assessment.createFrom;
const $$createType18 = report$0.DeviceReport.createFrom;
const $$createType19 = Info.createFrom;
