// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * A UUID is a Universally Unique Identifier as specified in RFC 9562.
 * 
 * UUIDs are comparable, such as with the == operator.
 */
export type UUID = string;
