// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as attestation$0 from "../attestation/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as credential$0 from "../credential/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as extension$0 from "../extension/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uuid$0 from "../../../../uuid/models.js";

/**
 * AuthenticatorGetInfoResponse is used in Metadata Statement specification as well, so json notation added.
 */
export class AuthenticatorGetInfoResponse {
    "versions": Versions;
    "extensions"?: extension$0.ExtensionIdentifier[];
    "aaguid": uuid$0.UUID;
    "options"?: { [_ in Option]?: boolean };
    "maxMsgSize"?: number;
    "pinUvAuthProtocols"?: PinUvAuthProtocol[];
    "maxCredentialCountInList"?: number;
    "maxCredentialIdLength"?: number;
    "transports"?: credential$0.AuthenticatorTransport[];
    "algorithms"?: credential$0.PublicKeyCredentialParameters[];
    "maxSerializedLargeBlobArray"?: number;
    "forcePINChange"?: boolean;
    "minPINLength"?: number;
    "firmwareVersion"?: number | null;
    "maxCredBlobLength"?: number;
    "maxRPIDsForSetMinPINLength"?: number | null;
    "preferredPlatformUvAttempts"?: number;
    "uvModality"?: UserVerify | null;
    "certifications"?: { [_ in string]?: number };
    "remainingDiscoverableCredentials"?: number | null;
    "vendorPrototypeConfigCommands"?: VendorCommandID[];
    "attestationFormats"?: attestation$0.AttestationStatementFormatIdentifier[];
    "uvCountSinceLastPinEntry"?: number | null;
    "longTouchForReset"?: boolean | null;
    "encIdentifier"?: string;
    "transportsForReset"?: credential$0.AuthenticatorTransport[];
    "pinComplexityPolicy"?: boolean | null;
    "pinComplexityPolicyURL"?: string;
    "maxPINLength"?: number;
    "encCredStoreState"?: string;
    "authenticatorConfigCommands"?: ConfigSubCommand[];

    /** Creates a new AuthenticatorGetInfoResponse instance. */
    constructor($$source: Partial<AuthenticatorGetInfoResponse> = {}) {
        if (!("versions" in $$source)) {
            this["versions"] = [];
        }
        if (!("aaguid" in $$source)) {
            this["aaguid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthenticatorGetInfoResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthenticatorGetInfoResponse {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        const $$createField5_0 = $$createType4;
        const $$createField8_0 = $$createType5;
        const $$createField9_0 = $$createType7;
        const $$createField18_0 = $$createType8;
        const $$createField20_0 = $$createType9;
        const $$createField21_0 = $$createType10;
        const $$createField24_0 = $Create.ByteSlice;
        const $$createField25_0 = $$createType5;
        const $$createField27_0 = $Create.ByteSlice;
        const $$createField29_0 = $Create.ByteSlice;
        const $$createField30_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("versions" in $$parsedSource) {
            $$parsedSource["versions"] = $$createField0_0($$parsedSource["versions"]);
        }
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField1_0($$parsedSource["extensions"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        if ("pinUvAuthProtocols" in $$parsedSource) {
            $$parsedSource["pinUvAuthProtocols"] = $$createField5_0($$parsedSource["pinUvAuthProtocols"]);
        }
        if ("transports" in $$parsedSource) {
            $$parsedSource["transports"] = $$createField8_0($$parsedSource["transports"]);
        }
        if ("algorithms" in $$parsedSource) {
            $$parsedSource["algorithms"] = $$createField9_0($$parsedSource["algorithms"]);
        }
        if ("certifications" in $$parsedSource) {
            $$parsedSource["certifications"] = $$createField18_0($$parsedSource["certifications"]);
        }
        if ("vendorPrototypeConfigCommands" in $$parsedSource) {
            $$parsedSource["vendorPrototypeConfigCommands"] = $$createField20_0($$parsedSource["vendorPrototypeConfigCommands"]);
        }
        if ("attestationFormats" in $$parsedSource) {
            $$parsedSource["attestationFormats"] = $$createField21_0($$parsedSource["attestationFormats"]);
        }
        if ("encIdentifier" in $$parsedSource) {
            $$parsedSource["encIdentifier"] = $$createField24_0($$parsedSource["encIdentifier"]);
        }
        if ("transportsForReset" in $$parsedSource) {
            $$parsedSource["transportsForReset"] = $$createField25_0($$parsedSource["transportsForReset"]);
        }
        if ("pinComplexityPolicyURL" in $$parsedSource) {
            $$parsedSource["pinComplexityPolicyURL"] = $$createField27_0($$parsedSource["pinComplexityPolicyURL"]);
        }
        if ("encCredStoreState" in $$parsedSource) {
            $$parsedSource["encCredStoreState"] = $$createField29_0($$parsedSource["encCredStoreState"]);
        }
        if ("authenticatorConfigCommands" in $$parsedSource) {
            $$parsedSource["authenticatorConfigCommands"] = $$createField30_0($$parsedSource["authenticatorConfigCommands"]);
        }
        return new AuthenticatorGetInfoResponse($$parsedSource as Partial<AuthenticatorGetInfoResponse>);
    }
}

export enum ConfigSubCommand {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    ConfigSubCommandEnableEnterpriseAttestation = 1,
    ConfigSubCommandToggleAlwaysUv = 2,
    ConfigSubCommandSetMinPINLength = 3,
    ConfigSubCommandEnableLongTouchForReset = 4,
};

export enum Option {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OptionPlatformDevice = "plat",
    OptionResidentKeys = "rk",
    OptionClientPIN = "clientPin",
    OptionUserPresence = "up",
    OptionUserVerification = "uv",
    OptionUvToken = "uvToken",
    OptionPinUvAuthToken = "pinUvAuthToken",
    OptionNoMcGaPermissionsWithClientPin = "noMcGaPermissionsWithClientPin",
    OptionLargeBlobs = "largeBlobs",
    OptionEnterpriseAttestation = "ep",
    OptionBioEnroll = "bioEnroll",
    OptionUserVerificationMgmtPreview = "userVerificationMgmtPreview",
    OptionUvBioEnroll = "uvBioEnroll",
    OptionAuthenticatorConfig = "authnrCfg",
    OptionUvAcfg = "uvAcfg",
    OptionCredentialManagement = "credMgmt",
    OptionPersistentCredentialManagementReadOnly = "perCredMgmtRO",
    OptionCredentialManagementPreview = "credentialMgmtPreview",
    OptionSetMinPINLength = "setMinPINLength",
    OptionMakeCredentialUvNotRequired = "makeCredUvNotRqd",
    OptionAlwaysUv = "alwaysUv",
};

export enum PinUvAuthProtocol {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    PinUvAuthProtocolOne = 1,
    PinUvAuthProtocolTwo = 2,
};

export enum UserVerify {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * FIDO Registry of Predefined Values 2.3 §3.1 User Verification Methods:
     * https://fidoalliance.org/specs/common-specs/fido-registry-v2.3-ps-20260105.html#user-verification-methods
     */
    UserVerifyPresenceInternal = 1,
    UserVerifyFingerprintInternal = 2,
    UserVerifyPasscodeInternal = 4,
    UserVerifyVoiceprintInternal = 8,
    UserVerifyFaceprintInternal = 16,
    UserVerifyLocationInternal = 32,
    UserVerifyEyeprintInternal = 64,
    UserVerifyPatternInternal = 128,
    UserVerifyHandprintInternal = 256,
    UserVerifyNone = 512,
    UserVerifyAll = 1024,
    UserVerifyPasscodeExternal = 2048,
    UserVerifyPatternExternal = 4096,
};

/**
 * VendorCommandID identifies a vendor-defined authenticatorConfig command.
 * CTAP assigns the complete unsigned 64-bit range to these identifiers.
 */
export type VendorCommandID = number;

export enum Version {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    FIDO_2_0 = "FIDO_2_0",
    FIDO_2_1_PRE = "FIDO_2_1_PRE",
    FIDO_2_1 = "FIDO_2_1",
    FIDO_2_3 = "FIDO_2_3",
    U2F_V2 = "U2F_V2",
};

export type Versions = Version[];

// Private type creation functions
var $$createType0 = (function $$initCreateType0(...args: any[]): any {
    if ($$createType0 === $$initCreateType0) {
        $$createType0 = $$createType1;
    }
    return $$createType0(...args);
});
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = credential$0.PublicKeyCredentialParameters.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = $Create.Array($Create.Any);
