// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Algorithm identifies an entry in the IANA COSE Algorithms registry.
 */
export enum Algorithm {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * AlgorithmES256 is ECDSA with SHA-256 on the P-256 curve.
     */
    AlgorithmES256 = -7,

    /**
     * AlgorithmESP256 is deterministic ECDSA with SHA-256 on the P-256 curve.
     */
    AlgorithmESP256 = -9,

    /**
     * AlgorithmES384 is ECDSA with SHA-384 on the P-384 curve.
     */
    AlgorithmES384 = -35,

    /**
     * AlgorithmESP384 is deterministic ECDSA with SHA-384 on the P-384 curve.
     */
    AlgorithmESP384 = -51,

    /**
     * AlgorithmES512 is ECDSA with SHA-512 on the P-521 curve.
     */
    AlgorithmES512 = -36,

    /**
     * AlgorithmESP512 is deterministic ECDSA with SHA-512 on the P-521 curve.
     */
    AlgorithmESP512 = -52,

    /**
     * AlgorithmES256K is ECDSA with SHA-256 on the secp256k1 curve.
     */
    AlgorithmES256K = -47,

    /**
     * AlgorithmEdDSA is EdDSA using a key-selected Edwards curve.
     */
    AlgorithmEdDSA = -8,

    /**
     * AlgorithmEd25519 is EdDSA using Ed25519.
     */
    AlgorithmEd25519 = -19,

    /**
     * AlgorithmRS256 is RSASSA-PKCS1-v1_5 with SHA-256.
     */
    AlgorithmRS256 = -257,

    /**
     * AlgorithmRS384 is RSASSA-PKCS1-v1_5 with SHA-384.
     */
    AlgorithmRS384 = -258,

    /**
     * AlgorithmRS512 is RSASSA-PKCS1-v1_5 with SHA-512.
     */
    AlgorithmRS512 = -259,

    /**
     * AlgorithmRS1 is RSASSA-PKCS1-v1_5 with SHA-1.
     */
    AlgorithmRS1 = -65535,

    /**
     * AlgorithmPS256 is RSASSA-PSS with SHA-256.
     */
    AlgorithmPS256 = -37,

    /**
     * AlgorithmPS384 is RSASSA-PSS with SHA-384.
     */
    AlgorithmPS384 = -38,

    /**
     * AlgorithmPS512 is RSASSA-PSS with SHA-512.
     */
    AlgorithmPS512 = -39,

    /**
     * AlgorithmECDHESHKDF256 is ECDH ES with HKDF-SHA-256.
     */
    AlgorithmECDHESHKDF256 = -25,

    /**
     * AlgorithmESP256SplitARKGPlaceholder is ESP256-split using a private key derived by ARKG-P256.
     */
    AlgorithmESP256SplitARKGPlaceholder = -65539,

    /**
     * AlgorithmARKGP256Placeholder identifies the ARKG-P256 instance.
     */
    AlgorithmARKGP256Placeholder = -65700,
};
