// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AttestationStatementFormatIdentifier is an enum consisting of IANA registered Attestation Statement Format Identifiers.
 * https://www.iana.org/assignments/webauthn/webauthn.xhtml
 */
export enum AttestationStatementFormatIdentifier {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AttestationStatementFormatIdentifierPacked = "packed",
    AttestationStatementFormatIdentifierTPM = "tpm",
    AttestationStatementFormatIdentifierAndroidKey = "android-key",
    AttestationStatementFormatIdentifierAndroidSafetyNet = "android-safetynet",
    AttestationStatementFormatIdentifierFIDOU2F = "fido-u2f",
    AttestationStatementFormatIdentifierApple = "apple",
    AttestationStatementFormatIdentifierNone = "none",
};

/**
 * Type describes the attestation evidence established by statement verification.
 */
export enum Type {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeNone = "none",
    TypeSelf = "self",
    TypeBasic = "basic",
    TypeUnsupported = "unsupported",
};
