// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum CredentialProtectionPolicy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CredentialProtectionPolicyUserVerificationOptional = "userVerificationOptional",
    CredentialProtectionPolicyUserVerificationOptionalWithCredentialIDList = "userVerificationOptionalWithCredentialIDList",
    CredentialProtectionPolicyUserVerificationRequired = "userVerificationRequired",
};

/**
 * ExtensionIdentifier is an enum consisting of IANA registered Extension Identifiers.
 * https://www.iana.org/assignments/webauthn/webauthn.xhtml
 */
export enum ExtensionIdentifier {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ExtensionIdentifierAppID = "appid",
    ExtensionIdentifierTxAuthSimple = "txAuthSimple",
    ExtensionIdentifierTxAuthGeneric = "txAuthGeneric",
    ExtensionIdentifierAuthnSelection = "authnSel",
    ExtensionIdentifierExtensions = "exts",
    ExtensionIdentifierUserVerificationIndex = "uvi",
    ExtensionIdentifierLocation = "loc",
    ExtensionIdentifierUserVerificationMethod = "uvm",
    ExtensionIdentifierCredentialProtection = "credProtect",
    ExtensionIdentifierCredentialBlob = "credBlob",
    ExtensionIdentifierLargeBlobKey = "largeBlobKey",
    ExtensionIdentifierMinPinLength = "minPinLength",
    ExtensionIdentifierPinComplexityPolicy = "pinComplexityPolicy",
    ExtensionIdentifierHMACSecret = "hmac-secret",
    ExtensionIdentifierHMACSecretMC = "hmac-secret-mc",
    ExtensionIdentifierAppIDExclude = "appidExclude",
    ExtensionIdentifierCredentialProperties = "credProps",
    ExtensionIdentifierLargeBlob = "largeBlob",
    ExtensionIdentifierPayment = "payment",
    ExtensionIdentifierThirdPartyPayment = "thirdPartyPayment",
    ExtensionIdentifierPreviewSign = "previewSign",
};

export enum LargeBlobSupport {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    LargeBlobSupportRequired = "required",
    LargeBlobSupportPreferred = "preferred",
};
