// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as protocol$0 from "../../ctap/protocol/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as uuid$0 from "../../../../uuid/models.js";

/**
 * AttestationTrustAssessment contains policy-neutral MDS trust facts. Status
 * reports are preserved so a relying party can apply stricter product policy.
 */
export class AttestationTrustAssessment {
    "status": AttestationTrustStatus;
    "metadataFound": boolean;
    "certificateChainTrusted"?: boolean | null;
    "authenticatorStatuses"?: AuthenticatorStatus[];
    "issues"?: AttestationTrustIssueCode[];

    /** Creates a new AttestationTrustAssessment instance. */
    constructor($$source: Partial<AttestationTrustAssessment> = {}) {
        if (!("status" in $$source)) {
            this["status"] = AttestationTrustStatus.$zero;
        }
        if (!("metadataFound" in $$source)) {
            this["metadataFound"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttestationTrustAssessment instance from a string or object.
     */
    static createFrom($$source: any = {}): AttestationTrustAssessment {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("authenticatorStatuses" in $$parsedSource) {
            $$parsedSource["authenticatorStatuses"] = $$createField3_0($$parsedSource["authenticatorStatuses"]);
        }
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField4_0($$parsedSource["issues"]);
        }
        return new AttestationTrustAssessment($$parsedSource as Partial<AttestationTrustAssessment>);
    }
}

/**
 * AttestationTrustIssueCode identifies a stable reason for an attestation
 * trust outcome.
 */
export enum AttestationTrustIssueCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AttestationTrustIssueMetadataNotFound = "mds.attestation.metadata_not_found",
    AttestationTrustIssueMetadataAAGUIDMismatch = "mds.attestation.metadata_aaguid_mismatch",
    AttestationTrustIssueEvidenceMalformed = "mds.attestation.evidence_malformed",
    AttestationTrustIssueEvidenceUnverified = "mds.attestation.evidence_unverified",
    AttestationTrustIssueFormatUnsupported = "mds.attestation.format_unsupported",
    AttestationTrustIssueCertificateChainMissing = "mds.attestation.certificate_chain_missing",
    AttestationTrustIssueCertificateChainMalformed = "mds.attestation.certificate_chain_malformed",
    AttestationTrustIssueAttestationRootsMissing = "mds.attestation.roots_missing",
    AttestationTrustIssueAttestationRootMalformed = "mds.attestation.root_malformed",
    AttestationTrustIssueCertificateChainUntrusted = "mds.attestation.certificate_chain_untrusted",
    AttestationTrustIssueAuthenticatorRevoked = "mds.attestation.authenticator_revoked",
    AttestationTrustIssueAttestationKeyCompromise = "mds.attestation.attestation_key_compromise",
    AttestationTrustIssueStatusCertificateMalformed = "mds.attestation.status_certificate_malformed",
};

/**
 * AttestationTrustStatus is the outcome of evaluating attestation evidence
 * against one verified MDS entry.
 */
export enum AttestationTrustStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AttestationTrustStatusTrusted = "trusted",
    AttestationTrustStatusUntrusted = "untrusted",
    AttestationTrustStatusUnavailable = "unavailable",
    AttestationTrustStatusNotApplicable = "not_applicable",
};

/**
 * AuthenticatorStatus is an MDS authenticator status value.
 */
export enum AuthenticatorStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthenticatorStatusNotFIDOCertified = "NOT_FIDO_CERTIFIED",
    AuthenticatorStatusFIDOCertified = "FIDO_CERTIFIED",
    AuthenticatorStatusUserVerificationBypass = "USER_VERIFICATION_BYPASS",
    AuthenticatorStatusAttestationKeyCompromise = "ATTESTATION_KEY_COMPROMISE",
    AuthenticatorStatusUserKeyRemoteCompromise = "USER_KEY_REMOTE_COMPROMISE",
    AuthenticatorStatusUserKeyPhysicalCompromise = "USER_KEY_PHYSICAL_COMPROMISE",
    AuthenticatorStatusUpdateAvailable = "UPDATE_AVAILABLE",
    AuthenticatorStatusRetired = "RETIRED",
    AuthenticatorStatusRevoked = "REVOKED",
    AuthenticatorStatusSelfAssertionSubmitted = "SELF_ASSERTION_SUBMITTED",
    AuthenticatorStatusFIDOCertifiedL1 = "FIDO_CERTIFIED_L1",
    AuthenticatorStatusFIDOCertifiedL1Plus = "FIDO_CERTIFIED_L1plus",
    AuthenticatorStatusFIDOCertifiedL2 = "FIDO_CERTIFIED_L2",
    AuthenticatorStatusFIDOCertifiedL2Plus = "FIDO_CERTIFIED_L2plus",
    AuthenticatorStatusFIDOCertifiedL3 = "FIDO_CERTIFIED_L3",
    AuthenticatorStatusFIDOCertifiedL3Plus = "FIDO_CERTIFIED_L3plus",
    AuthenticatorStatusFIPS140CertifiedL1 = "FIPS140_CERTIFIED_L1",
    AuthenticatorStatusFIPS140CertifiedL2 = "FIPS140_CERTIFIED_L2",
    AuthenticatorStatusFIPS140CertifiedL3 = "FIPS140_CERTIFIED_L3",
    AuthenticatorStatusFIPS140CertifiedL4 = "FIPS140_CERTIFIED_L4",
};

/**
 * BiometricStatusReport describes biometric certification status for an authenticator model.
 */
export class BiometricStatusReport {
    "certLevel": number;
    "modality": string;
    "effectiveDate"?: string | null;
    "certificationDescriptor"?: string | null;
    "certificateNumber"?: string | null;
    "certificationPolicyVersion"?: string | null;
    "certificationRequirementsVersion"?: string | null;

    /** Creates a new BiometricStatusReport instance. */
    constructor($$source: Partial<BiometricStatusReport> = {}) {
        if (!("certLevel" in $$source)) {
            this["certLevel"] = 0;
        }
        if (!("modality" in $$source)) {
            this["modality"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BiometricStatusReport instance from a string or object.
     */
    static createFrom($$source: any = {}): BiometricStatusReport {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BiometricStatusReport($$parsedSource as Partial<BiometricStatusReport>);
    }
}

export class DisplayPNGCharacteristicsDescriptor {
    "width": number;
    "height": number;
    "bitDepth": number;
    "colorType": number;
    "compression": number;
    "filter": number;
    "interlace": number;
    "plte": RGBPaletteEntry[];

    /** Creates a new DisplayPNGCharacteristicsDescriptor instance. */
    constructor($$source: Partial<DisplayPNGCharacteristicsDescriptor> = {}) {
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("bitDepth" in $$source)) {
            this["bitDepth"] = 0;
        }
        if (!("colorType" in $$source)) {
            this["colorType"] = 0;
        }
        if (!("compression" in $$source)) {
            this["compression"] = 0;
        }
        if (!("filter" in $$source)) {
            this["filter"] = 0;
        }
        if (!("interlace" in $$source)) {
            this["interlace"] = 0;
        }
        if (!("plte" in $$source)) {
            this["plte"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DisplayPNGCharacteristicsDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): DisplayPNGCharacteristicsDescriptor {
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("plte" in $$parsedSource) {
            $$parsedSource["plte"] = $$createField7_0($$parsedSource["plte"]);
        }
        return new DisplayPNGCharacteristicsDescriptor($$parsedSource as Partial<DisplayPNGCharacteristicsDescriptor>);
    }
}

export class ECDAATrustAnchor {
    "X": string;
    "Y": string;
    "c": string;
    "sx": string;
    "sy": string;
    "G1Curve": string;

    /** Creates a new ECDAATrustAnchor instance. */
    constructor($$source: Partial<ECDAATrustAnchor> = {}) {
        if (!("X" in $$source)) {
            this["X"] = "";
        }
        if (!("Y" in $$source)) {
            this["Y"] = "";
        }
        if (!("c" in $$source)) {
            this["c"] = "";
        }
        if (!("sx" in $$source)) {
            this["sx"] = "";
        }
        if (!("sy" in $$source)) {
            this["sy"] = "";
        }
        if (!("G1Curve" in $$source)) {
            this["G1Curve"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ECDAATrustAnchor instance from a string or object.
     */
    static createFrom($$source: any = {}): ECDAATrustAnchor {
        const $$createField0_0 = $Create.ByteSlice;
        const $$createField1_0 = $Create.ByteSlice;
        const $$createField2_0 = $Create.ByteSlice;
        const $$createField3_0 = $Create.ByteSlice;
        const $$createField4_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("X" in $$parsedSource) {
            $$parsedSource["X"] = $$createField0_0($$parsedSource["X"]);
        }
        if ("Y" in $$parsedSource) {
            $$parsedSource["Y"] = $$createField1_0($$parsedSource["Y"]);
        }
        if ("c" in $$parsedSource) {
            $$parsedSource["c"] = $$createField2_0($$parsedSource["c"]);
        }
        if ("sx" in $$parsedSource) {
            $$parsedSource["sx"] = $$createField3_0($$parsedSource["sx"]);
        }
        if ("sy" in $$parsedSource) {
            $$parsedSource["sy"] = $$createField4_0($$parsedSource["sy"]);
        }
        return new ECDAATrustAnchor($$parsedSource as Partial<ECDAATrustAnchor>);
    }
}

export class ExtensionDescriptor {
    "id": string;
    "tag": number;
    "data": string;
    "fail_if_unknown": boolean;

    /** Creates a new ExtensionDescriptor instance. */
    constructor($$source: Partial<ExtensionDescriptor> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("tag" in $$source)) {
            this["tag"] = 0;
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }
        if (!("fail_if_unknown" in $$source)) {
            this["fail_if_unknown"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtensionDescriptor instance from a string or object.
     */
    static createFrom($$source: any = {}): ExtensionDescriptor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExtensionDescriptor($$parsedSource as Partial<ExtensionDescriptor>);
    }
}

/**
 * LookupResult is the public result of a verified FIDO Metadata Service AAGUID lookup.
 */
export class LookupResult {
    "aaguid": uuid$0.UUID;
    "found": boolean;
    "entry"?: PayloadEntry | null;
    "blobNumber": number;
    "source": string;
    "cached": boolean;
    "cachedAt": string;

    /** Creates a new LookupResult instance. */
    constructor($$source: Partial<LookupResult> = {}) {
        if (!("aaguid" in $$source)) {
            this["aaguid"] = "";
        }
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("blobNumber" in $$source)) {
            this["blobNumber"] = 0;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("cached" in $$source)) {
            this["cached"] = false;
        }
        if (!("cachedAt" in $$source)) {
            this["cachedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LookupResult instance from a string or object.
     */
    static createFrom($$source: any = {}): LookupResult {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entry" in $$parsedSource) {
            $$parsedSource["entry"] = $$createField2_0($$parsedSource["entry"]);
        }
        return new LookupResult($$parsedSource as Partial<LookupResult>);
    }
}

export class MetadataStatement {
    "legalHeader"?: string | null;
    "aaid"?: string | null;
    "aaguid"?: uuid$0.UUID | null;
    "attestationCertificateKeyIdentifiers"?: string[];
    "friendlyNames"?: { [_ in string]?: string };
    "description"?: string;
    "alternativeDescriptions"?: { [_ in string]?: string };
    "authenticatorVersion": number | null;
    "protocolFamily": string;
    "schema": number;
    "upv": Version[];
    "authenticationAlgorithms": string[];
    "publicKeyAlgAndEncodings": string[];
    "attestationTypes": string[];
    "userVerificationDetails": any[];
    "keyProtection": string[];
    "isKeyRestricted"?: boolean | null;
    "isFreshUserVerificationRequired"?: boolean | null;
    "matcherProtection": string[];
    "cryptoStrength"?: number | null;
    "attachmentHint"?: string[];
    "tcDisplay": string[];
    "tcDisplayContentType"?: string | null;
    "tcDisplayPNGCharacteristics"?: DisplayPNGCharacteristicsDescriptor[];
    "attestationRootCertificates": string[];
    "ECDAATrustAnchor"?: ECDAATrustAnchor[];
    "icon"?: string | null;
    "iconDark"?: string | null;
    "providerLogoLight"?: string | null;
    "providerLogoDark"?: string | null;
    "extensionDescriptor"?: ExtensionDescriptor[];
    "multiDeviceCredentialSupport": string | null;
    "authenticatorGetInfo"?: protocol$0.AuthenticatorGetInfoResponse;
    "cxConfigURL": string | null;

    /** Creates a new MetadataStatement instance. */
    constructor($$source: Partial<MetadataStatement> = {}) {
        if (!("authenticatorVersion" in $$source)) {
            this["authenticatorVersion"] = null;
        }
        if (!("protocolFamily" in $$source)) {
            this["protocolFamily"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = 0;
        }
        if (!("upv" in $$source)) {
            this["upv"] = [];
        }
        if (!("authenticationAlgorithms" in $$source)) {
            this["authenticationAlgorithms"] = [];
        }
        if (!("publicKeyAlgAndEncodings" in $$source)) {
            this["publicKeyAlgAndEncodings"] = [];
        }
        if (!("attestationTypes" in $$source)) {
            this["attestationTypes"] = [];
        }
        if (!("userVerificationDetails" in $$source)) {
            this["userVerificationDetails"] = [];
        }
        if (!("keyProtection" in $$source)) {
            this["keyProtection"] = [];
        }
        if (!("matcherProtection" in $$source)) {
            this["matcherProtection"] = [];
        }
        if (!("tcDisplay" in $$source)) {
            this["tcDisplay"] = [];
        }
        if (!("attestationRootCertificates" in $$source)) {
            this["attestationRootCertificates"] = [];
        }
        if (!("multiDeviceCredentialSupport" in $$source)) {
            this["multiDeviceCredentialSupport"] = null;
        }
        if (!("cxConfigURL" in $$source)) {
            this["cxConfigURL"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetadataStatement instance from a string or object.
     */
    static createFrom($$source: any = {}): MetadataStatement {
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType7;
        const $$createField6_0 = $$createType7;
        const $$createField10_0 = $$createType9;
        const $$createField11_0 = $$createType6;
        const $$createField12_0 = $$createType6;
        const $$createField13_0 = $$createType6;
        const $$createField14_0 = $$createType10;
        const $$createField15_0 = $$createType6;
        const $$createField18_0 = $$createType6;
        const $$createField20_0 = $$createType6;
        const $$createField21_0 = $$createType6;
        const $$createField23_0 = $$createType12;
        const $$createField24_0 = $$createType6;
        const $$createField25_0 = $$createType14;
        const $$createField30_0 = $$createType16;
        const $$createField32_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attestationCertificateKeyIdentifiers" in $$parsedSource) {
            $$parsedSource["attestationCertificateKeyIdentifiers"] = $$createField3_0($$parsedSource["attestationCertificateKeyIdentifiers"]);
        }
        if ("friendlyNames" in $$parsedSource) {
            $$parsedSource["friendlyNames"] = $$createField4_0($$parsedSource["friendlyNames"]);
        }
        if ("alternativeDescriptions" in $$parsedSource) {
            $$parsedSource["alternativeDescriptions"] = $$createField6_0($$parsedSource["alternativeDescriptions"]);
        }
        if ("upv" in $$parsedSource) {
            $$parsedSource["upv"] = $$createField10_0($$parsedSource["upv"]);
        }
        if ("authenticationAlgorithms" in $$parsedSource) {
            $$parsedSource["authenticationAlgorithms"] = $$createField11_0($$parsedSource["authenticationAlgorithms"]);
        }
        if ("publicKeyAlgAndEncodings" in $$parsedSource) {
            $$parsedSource["publicKeyAlgAndEncodings"] = $$createField12_0($$parsedSource["publicKeyAlgAndEncodings"]);
        }
        if ("attestationTypes" in $$parsedSource) {
            $$parsedSource["attestationTypes"] = $$createField13_0($$parsedSource["attestationTypes"]);
        }
        if ("userVerificationDetails" in $$parsedSource) {
            $$parsedSource["userVerificationDetails"] = $$createField14_0($$parsedSource["userVerificationDetails"]);
        }
        if ("keyProtection" in $$parsedSource) {
            $$parsedSource["keyProtection"] = $$createField15_0($$parsedSource["keyProtection"]);
        }
        if ("matcherProtection" in $$parsedSource) {
            $$parsedSource["matcherProtection"] = $$createField18_0($$parsedSource["matcherProtection"]);
        }
        if ("attachmentHint" in $$parsedSource) {
            $$parsedSource["attachmentHint"] = $$createField20_0($$parsedSource["attachmentHint"]);
        }
        if ("tcDisplay" in $$parsedSource) {
            $$parsedSource["tcDisplay"] = $$createField21_0($$parsedSource["tcDisplay"]);
        }
        if ("tcDisplayPNGCharacteristics" in $$parsedSource) {
            $$parsedSource["tcDisplayPNGCharacteristics"] = $$createField23_0($$parsedSource["tcDisplayPNGCharacteristics"]);
        }
        if ("attestationRootCertificates" in $$parsedSource) {
            $$parsedSource["attestationRootCertificates"] = $$createField24_0($$parsedSource["attestationRootCertificates"]);
        }
        if ("ECDAATrustAnchor" in $$parsedSource) {
            $$parsedSource["ECDAATrustAnchor"] = $$createField25_0($$parsedSource["ECDAATrustAnchor"]);
        }
        if ("extensionDescriptor" in $$parsedSource) {
            $$parsedSource["extensionDescriptor"] = $$createField30_0($$parsedSource["extensionDescriptor"]);
        }
        if ("authenticatorGetInfo" in $$parsedSource) {
            $$parsedSource["authenticatorGetInfo"] = $$createField32_0($$parsedSource["authenticatorGetInfo"]);
        }
        return new MetadataStatement($$parsedSource as Partial<MetadataStatement>);
    }
}

/**
 * PayloadEntry contains the MDS payload entry for one authenticator model.
 */
export class PayloadEntry {
    "aaid"?: string | null;
    "aaguid"?: uuid$0.UUID;
    "attestationCertificateKeyIdentifiers"?: string[];
    "metadataStatement"?: MetadataStatement;
    "biometricStatusReports"?: BiometricStatusReport[];
    "statusReports"?: StatusReport[];
    "timeOfLastStatusChange"?: string;
    "rogueListURL"?: string | null;
    "rogueListHash"?: string | null;

    /** Creates a new PayloadEntry instance. */
    constructor($$source: Partial<PayloadEntry> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PayloadEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): PayloadEntry {
        const $$createField2_0 = $$createType6;
        const $$createField3_0 = $$createType18;
        const $$createField4_0 = $$createType20;
        const $$createField5_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attestationCertificateKeyIdentifiers" in $$parsedSource) {
            $$parsedSource["attestationCertificateKeyIdentifiers"] = $$createField2_0($$parsedSource["attestationCertificateKeyIdentifiers"]);
        }
        if ("metadataStatement" in $$parsedSource) {
            $$parsedSource["metadataStatement"] = $$createField3_0($$parsedSource["metadataStatement"]);
        }
        if ("biometricStatusReports" in $$parsedSource) {
            $$parsedSource["biometricStatusReports"] = $$createField4_0($$parsedSource["biometricStatusReports"]);
        }
        if ("statusReports" in $$parsedSource) {
            $$parsedSource["statusReports"] = $$createField5_0($$parsedSource["statusReports"]);
        }
        return new PayloadEntry($$parsedSource as Partial<PayloadEntry>);
    }
}

export class RGBPaletteEntry {
    "r": number | null;
    "g": number | null;
    "b": number | null;

    /** Creates a new RGBPaletteEntry instance. */
    constructor($$source: Partial<RGBPaletteEntry> = {}) {
        if (!("r" in $$source)) {
            this["r"] = null;
        }
        if (!("g" in $$source)) {
            this["g"] = null;
        }
        if (!("b" in $$source)) {
            this["b"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RGBPaletteEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): RGBPaletteEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RGBPaletteEntry($$parsedSource as Partial<RGBPaletteEntry>);
    }
}

/**
 * StatusReport describes the current or historical status of an authenticator model.
 */
export class StatusReport {
    "status": AuthenticatorStatus;
    "effectiveDate"?: string | null;
    "authenticatorVersion"?: number | null;
    "batchCertificate"?: string | null;
    "certificate"?: string | null;
    "url"?: string | null;
    "certificationDescriptor"?: string | null;
    "certificateNumber"?: string | null;
    "certificationPolicyVersion"?: string | null;
    "certificationProfiles"?: string[];
    "certificationRequirementsVersion"?: string | null;
    "sunsetDate"?: string | null;
    "fipsRevision"?: number | null;
    "fipsPhysicalSecurityLevel"?: number | null;

    /** Creates a new StatusReport instance. */
    constructor($$source: Partial<StatusReport> = {}) {
        if (!("status" in $$source)) {
            this["status"] = AuthenticatorStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusReport instance from a string or object.
     */
    static createFrom($$source: any = {}): StatusReport {
        const $$createField9_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("certificationProfiles" in $$parsedSource) {
            $$parsedSource["certificationProfiles"] = $$createField9_0($$parsedSource["certificationProfiles"]);
        }
        return new StatusReport($$parsedSource as Partial<StatusReport>);
    }
}

export class Version {
    "major": number;
    "minor": number;

    /** Creates a new Version instance. */
    constructor($$source: Partial<Version> = {}) {
        if (!("major" in $$source)) {
            this["major"] = 0;
        }
        if (!("minor" in $$source)) {
            this["minor"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Version instance from a string or object.
     */
    static createFrom($$source: any = {}): Version {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Version($$parsedSource as Partial<Version>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = RGBPaletteEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = PayloadEntry.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = Version.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($Create.Any);
const $$createType11 = DisplayPNGCharacteristicsDescriptor.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = ECDAATrustAnchor.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = ExtensionDescriptor.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = protocol$0.AuthenticatorGetInfoResponse.createFrom;
const $$createType18 = MetadataStatement.createFrom;
const $$createType19 = BiometricStatusReport.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = StatusReport.createFrom;
const $$createType22 = $Create.Array($$createType21);
