// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as attestation$0 from "../../github.com/telesma-app/ctap/attestation/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as credential$0 from "../../github.com/telesma-app/ctap/credential/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as webauthn$1 from "../../github.com/telesma-app/ctap/webauthn/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ctapkit$0 from "../../github.com/telesma-app/kit/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../github.com/telesma-app/kit/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../github.com/telesma-app/kit/model/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as credentials$0 from "../../github.com/telesma-app/kit/model/credentials/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as failure$0 from "../../github.com/telesma-app/kit/model/failure/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as inspect$0 from "../../github.com/telesma-app/kit/model/inspect/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as largeblobs$0 from "../../github.com/telesma-app/kit/model/largeblobs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as operation$0 from "../../github.com/telesma-app/kit/model/operation/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as report$0 from "../../github.com/telesma-app/kit/model/report/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as webauthn$0 from "../../github.com/telesma-app/kit/model/webauthn/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$1 from "../../github.com/telesma-app/mds/model/models.js";

export class ActiveSelection {
    "id": SelectionID;
    "attachmentId": report$0.AttachmentID;

    /** Creates a new ActiveSelection instance. */
    constructor($$source: Partial<ActiveSelection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("attachmentId" in $$source)) {
            this["attachmentId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActiveSelection instance from a string or object.
     */
    static createFrom($$source: any = {}): ActiveSelection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActiveSelection($$parsedSource as Partial<ActiveSelection>);
    }
}

export class AlwaysUVRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;
    "target": config$0.AlwaysUVTarget;
    "dryRun"?: boolean;

    /** Creates a new AlwaysUVRequest instance. */
    constructor($$source: Partial<AlwaysUVRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = config$0.AlwaysUVTarget.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlwaysUVRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AlwaysUVRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AlwaysUVRequest($$parsedSource as Partial<AlwaysUVRequest>);
    }
}

export class AuthenticatorConfigEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: config$0.AuthenticatorConfigOutput | null;

    /** Creates a new AuthenticatorConfigEnvelope instance. */
    constructor($$source: Partial<AuthenticatorConfigEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthenticatorConfigEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthenticatorConfigEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new AuthenticatorConfigEnvelope($$parsedSource as Partial<AuthenticatorConfigEnvelope>);
    }
}

export class AuthenticatorSessionSnapshot {
    "devices": report$0.DeviceReport[];
    "selection"?: ActiveSelection | null;
    "error"?: failure$0.Failure | null;

    /** Creates a new AuthenticatorSessionSnapshot instance. */
    constructor($$source: Partial<AuthenticatorSessionSnapshot> = {}) {
        if (!("devices" in $$source)) {
            this["devices"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthenticatorSessionSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthenticatorSessionSnapshot {
        const $$createField0_0 = $$createType5;
        const $$createField1_0 = $$createType7;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("devices" in $$parsedSource) {
            $$parsedSource["devices"] = $$createField0_0($$parsedSource["devices"]);
        }
        if ("selection" in $$parsedSource) {
            $$parsedSource["selection"] = $$createField1_0($$parsedSource["selection"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField2_0($$parsedSource["error"]);
        }
        return new AuthenticatorSessionSnapshot($$parsedSource as Partial<AuthenticatorSessionSnapshot>);
    }
}

export class BioEnrollEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: config$0.BioEnrollOutput | null;

    /** Creates a new BioEnrollEnvelope instance. */
    constructor($$source: Partial<BioEnrollEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioEnrollEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): BioEnrollEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new BioEnrollEnvelope($$parsedSource as Partial<BioEnrollEnvelope>);
    }
}

export class BioEnrollRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;
    "timeoutMilliseconds"?: number;
    "dryRun"?: boolean;

    /** Creates a new BioEnrollRequest instance. */
    constructor($$source: Partial<BioEnrollRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioEnrollRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BioEnrollRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BioEnrollRequest($$parsedSource as Partial<BioEnrollRequest>);
    }
}

export class BioListEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: config$0.BioListReport | null;

    /** Creates a new BioListEnvelope instance. */
    constructor($$source: Partial<BioListEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioListEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): BioListEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new BioListEnvelope($$parsedSource as Partial<BioListEnvelope>);
    }
}

export class BioMutationEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: config$0.BioMutationOutput | null;

    /** Creates a new BioMutationEnvelope instance. */
    constructor($$source: Partial<BioMutationEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioMutationEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): BioMutationEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new BioMutationEnvelope($$parsedSource as Partial<BioMutationEnvelope>);
    }
}

export class BioRemoveRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;
    "templateIDHex": string;
    "dryRun"?: boolean;

    /** Creates a new BioRemoveRequest instance. */
    constructor($$source: Partial<BioRemoveRequest> = {}) {
        if (!("templateIDHex" in $$source)) {
            this["templateIDHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioRemoveRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BioRemoveRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BioRemoveRequest($$parsedSource as Partial<BioRemoveRequest>);
    }
}

export class BioRenameRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;
    "templateIDHex": string;
    "friendlyName": string;
    "dryRun"?: boolean;

    /** Creates a new BioRenameRequest instance. */
    constructor($$source: Partial<BioRenameRequest> = {}) {
        if (!("templateIDHex" in $$source)) {
            this["templateIDHex"] = "";
        }
        if (!("friendlyName" in $$source)) {
            this["friendlyName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioRenameRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): BioRenameRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BioRenameRequest($$parsedSource as Partial<BioRenameRequest>);
    }
}

export class BioSensorEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: config$0.BioSensorReport | null;

    /** Creates a new BioSensorEnvelope instance. */
    constructor($$source: Partial<BioSensorEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BioSensorEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): BioSensorEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new BioSensorEnvelope($$parsedSource as Partial<BioSensorEnvelope>);
    }
}

export class CancelOperationRequest {
    "operationId": OperationID;

    /** Creates a new CancelOperationRequest instance. */
    constructor($$source: Partial<CancelOperationRequest> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CancelOperationRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CancelOperationRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CancelOperationRequest($$parsedSource as Partial<CancelOperationRequest>);
    }
}

export class ConfigStatusEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: config$0.StatusReport | null;

    /** Creates a new ConfigStatusEnvelope instance. */
    constructor($$source: Partial<ConfigStatusEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigStatusEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): ConfigStatusEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new ConfigStatusEnvelope($$parsedSource as Partial<ConfigStatusEnvelope>);
    }
}

export class CredentialDeleteEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: credentials$0.DeleteOutput | null;

    /** Creates a new CredentialDeleteEnvelope instance. */
    constructor($$source: Partial<CredentialDeleteEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialDeleteEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialDeleteEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new CredentialDeleteEnvelope($$parsedSource as Partial<CredentialDeleteEnvelope>);
    }
}

export class CredentialDeleteRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;
    "credentialIDHex": string;
    "dryRun"?: boolean;

    /** Creates a new CredentialDeleteRequest instance. */
    constructor($$source: Partial<CredentialDeleteRequest> = {}) {
        if (!("credentialIDHex" in $$source)) {
            this["credentialIDHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialDeleteRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialDeleteRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialDeleteRequest($$parsedSource as Partial<CredentialDeleteRequest>);
    }
}

export class CredentialUpdateEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: credentials$0.UpdateUserOutput | null;

    /** Creates a new CredentialUpdateEnvelope instance. */
    constructor($$source: Partial<CredentialUpdateEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialUpdateEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialUpdateEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new CredentialUpdateEnvelope($$parsedSource as Partial<CredentialUpdateEnvelope>);
    }
}

export class CredentialUpdateRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;
    "target": credentials$0.CredentialTarget;
    "name"?: string;
    "displayName"?: string;
    "nameProvided"?: boolean;
    "displayProvided"?: boolean;
    "dryRun"?: boolean;

    /** Creates a new CredentialUpdateRequest instance. */
    constructor($$source: Partial<CredentialUpdateRequest> = {}) {
        if (!("target" in $$source)) {
            this["target"] = (new credentials$0.CredentialTarget());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialUpdateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialUpdateRequest {
        const $$createField1_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("target" in $$parsedSource) {
            $$parsedSource["target"] = $$createField1_0($$parsedSource["target"]);
        }
        return new CredentialUpdateRequest($$parsedSource as Partial<CredentialUpdateRequest>);
    }
}

export class CredentialsEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: credentials$0.InventoryReport | null;

    /** Creates a new CredentialsEnvelope instance. */
    constructor($$source: Partial<CredentialsEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialsEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialsEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new CredentialsEnvelope($$parsedSource as Partial<CredentialsEnvelope>);
    }
}

export class DerivePreviewSignARKGP256Request {
    "generatedKey": webauthn$0.PreviewSignGeneratedKey;
    "context": string;

    /** Creates a new DerivePreviewSignARKGP256Request instance. */
    constructor($$source: Partial<DerivePreviewSignARKGP256Request> = {}) {
        if (!("generatedKey" in $$source)) {
            this["generatedKey"] = (new webauthn$0.PreviewSignGeneratedKey());
        }
        if (!("context" in $$source)) {
            this["context"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DerivePreviewSignARKGP256Request instance from a string or object.
     */
    static createFrom($$source: any = {}): DerivePreviewSignARKGP256Request {
        const $$createField0_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("generatedKey" in $$parsedSource) {
            $$parsedSource["generatedKey"] = $$createField0_0($$parsedSource["generatedKey"]);
        }
        return new DerivePreviewSignARKGP256Request($$parsedSource as Partial<DerivePreviewSignARKGP256Request>);
    }
}

export class DiscoveryChangedEnvelope {
    "snapshot": AuthenticatorSessionSnapshot;

    /** Creates a new DiscoveryChangedEnvelope instance. */
    constructor($$source: Partial<DiscoveryChangedEnvelope> = {}) {
        if (!("snapshot" in $$source)) {
            this["snapshot"] = (new AuthenticatorSessionSnapshot());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoveryChangedEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): DiscoveryChangedEnvelope {
        const $$createField0_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("snapshot" in $$parsedSource) {
            $$parsedSource["snapshot"] = $$createField0_0($$parsedSource["snapshot"]);
        }
        return new DiscoveryChangedEnvelope($$parsedSource as Partial<DiscoveryChangedEnvelope>);
    }
}

export class EnableEnterpriseAttestationRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;
    "dryRun"?: boolean;

    /** Creates a new EnableEnterpriseAttestationRequest instance. */
    constructor($$source: Partial<EnableEnterpriseAttestationRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnableEnterpriseAttestationRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): EnableEnterpriseAttestationRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnableEnterpriseAttestationRequest($$parsedSource as Partial<EnableEnterpriseAttestationRequest>);
    }
}

export class EnableLongTouchForResetRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;
    "dryRun"?: boolean;

    /** Creates a new EnableLongTouchForResetRequest instance. */
    constructor($$source: Partial<EnableLongTouchForResetRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnableLongTouchForResetRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): EnableLongTouchForResetRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnableLongTouchForResetRequest($$parsedSource as Partial<EnableLongTouchForResetRequest>);
    }
}

export class GetAssertionEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: webauthn$0.GetAssertionOutput | null;

    /** Creates a new GetAssertionEnvelope instance. */
    constructor($$source: Partial<GetAssertionEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAssertionEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType28;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new GetAssertionEnvelope($$parsedSource as Partial<GetAssertionEnvelope>);
    }
}

export class GetAssertionRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;
    "rpID": string;
    "clientDataJSON": string;
    "allowList"?: credential$0.PublicKeyCredentialDescriptor[];
    "options"?: webauthn$0.AuthenticatorOptions;
    "extensions"?: webauthn$1.GetAuthenticationExtensionsClientInputs | null;
    "dryRun"?: boolean;

    /** Creates a new GetAssertionRequest instance. */
    constructor($$source: Partial<GetAssertionRequest> = {}) {
        if (!("rpID" in $$source)) {
            this["rpID"] = "";
        }
        if (!("clientDataJSON" in $$source)) {
            this["clientDataJSON"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAssertionRequest {
        const $$createField2_0 = $Create.ByteSlice;
        const $$createField3_0 = $$createType30;
        const $$createField4_0 = $$createType31;
        const $$createField5_0 = $$createType33;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("clientDataJSON" in $$parsedSource) {
            $$parsedSource["clientDataJSON"] = $$createField2_0($$parsedSource["clientDataJSON"]);
        }
        if ("allowList" in $$parsedSource) {
            $$parsedSource["allowList"] = $$createField3_0($$parsedSource["allowList"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField4_0($$parsedSource["options"]);
        }
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField5_0($$parsedSource["extensions"]);
        }
        return new GetAssertionRequest($$parsedSource as Partial<GetAssertionRequest>);
    }
}

export class GetAssertionVerificationRequest {
    "input": webauthn$0.GetAssertionInput;
    "result": webauthn$0.GetAssertionResult;
    "verificationMaterial"?: webauthn$0.CredentialVerificationMaterial[];

    /** Creates a new GetAssertionVerificationRequest instance. */
    constructor($$source: Partial<GetAssertionVerificationRequest> = {}) {
        if (!("input" in $$source)) {
            this["input"] = (new webauthn$0.GetAssertionInput());
        }
        if (!("result" in $$source)) {
            this["result"] = (new webauthn$0.GetAssertionResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionVerificationRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAssertionVerificationRequest {
        const $$createField0_0 = $$createType34;
        const $$createField1_0 = $$createType35;
        const $$createField2_0 = $$createType37;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("input" in $$parsedSource) {
            $$parsedSource["input"] = $$createField0_0($$parsedSource["input"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        if ("verificationMaterial" in $$parsedSource) {
            $$parsedSource["verificationMaterial"] = $$createField2_0($$parsedSource["verificationMaterial"]);
        }
        return new GetAssertionVerificationRequest($$parsedSource as Partial<GetAssertionVerificationRequest>);
    }
}

export class InspectEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: inspect$0.Result | null;

    /** Creates a new InspectEnvelope instance. */
    constructor($$source: Partial<InspectEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InspectEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): InspectEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType39;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new InspectEnvelope($$parsedSource as Partial<InspectEnvelope>);
    }
}

export class InteractionAnswer {
    "interactionId": InteractionID;
    "pin"?: string;
    "canceled"?: boolean;

    /** Creates a new InteractionAnswer instance. */
    constructor($$source: Partial<InteractionAnswer> = {}) {
        if (!("interactionId" in $$source)) {
            this["interactionId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InteractionAnswer instance from a string or object.
     */
    static createFrom($$source: any = {}): InteractionAnswer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InteractionAnswer($$parsedSource as Partial<InteractionAnswer>);
    }
}

export type InteractionID = string;

export class InteractionPrompt {
    "interactionId": InteractionID;
    "operationId": OperationID;
    "selectionId": SelectionID;
    "request": model$0.InteractionRequest;

    /** Creates a new InteractionPrompt instance. */
    constructor($$source: Partial<InteractionPrompt> = {}) {
        if (!("interactionId" in $$source)) {
            this["interactionId"] = "";
        }
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("request" in $$source)) {
            this["request"] = (new model$0.InteractionRequest());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InteractionPrompt instance from a string or object.
     */
    static createFrom($$source: any = {}): InteractionPrompt {
        const $$createField3_0 = $$createType40;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("request" in $$parsedSource) {
            $$parsedSource["request"] = $$createField3_0($$parsedSource["request"]);
        }
        return new InteractionPrompt($$parsedSource as Partial<InteractionPrompt>);
    }
}

export class LargeBlobDecodeEnvelope {
    "result"?: largeblobs$0.DecodeResult | null;
    "error"?: failure$0.Failure | null;

    /** Creates a new LargeBlobDecodeEnvelope instance. */
    constructor($$source: Partial<LargeBlobDecodeEnvelope> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobDecodeEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobDecodeEnvelope {
        const $$createField0_0 = $$createType42;
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField0_0($$parsedSource["result"]);
        }
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField1_0($$parsedSource["error"]);
        }
        return new LargeBlobDecodeEnvelope($$parsedSource as Partial<LargeBlobDecodeEnvelope>);
    }
}

export class LargeBlobDecodeRequest {
    "rawHex": string;
    "mode": largeblobs$0.DecodeMode;

    /** Creates a new LargeBlobDecodeRequest instance. */
    constructor($$source: Partial<LargeBlobDecodeRequest> = {}) {
        if (!("rawHex" in $$source)) {
            this["rawHex"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = largeblobs$0.DecodeMode.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobDecodeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobDecodeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LargeBlobDecodeRequest($$parsedSource as Partial<LargeBlobDecodeRequest>);
    }
}

export class LargeBlobDeleteRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;
    "credentialIDHex": string;
    "dryRun"?: boolean;

    /** Creates a new LargeBlobDeleteRequest instance. */
    constructor($$source: Partial<LargeBlobDeleteRequest> = {}) {
        if (!("credentialIDHex" in $$source)) {
            this["credentialIDHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobDeleteRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobDeleteRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LargeBlobDeleteRequest($$parsedSource as Partial<LargeBlobDeleteRequest>);
    }
}

export class LargeBlobGarbageCollectRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;
    "dryRun"?: boolean;

    /** Creates a new LargeBlobGarbageCollectRequest instance. */
    constructor($$source: Partial<LargeBlobGarbageCollectRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobGarbageCollectRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobGarbageCollectRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LargeBlobGarbageCollectRequest($$parsedSource as Partial<LargeBlobGarbageCollectRequest>);
    }
}

export class LargeBlobListEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: largeblobs$0.ListReport | null;

    /** Creates a new LargeBlobListEnvelope instance. */
    constructor($$source: Partial<LargeBlobListEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobListEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobListEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType44;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new LargeBlobListEnvelope($$parsedSource as Partial<LargeBlobListEnvelope>);
    }
}

export class LargeBlobMutationEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: largeblobs$0.MutationOutput | null;

    /** Creates a new LargeBlobMutationEnvelope instance. */
    constructor($$source: Partial<LargeBlobMutationEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobMutationEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobMutationEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType46;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new LargeBlobMutationEnvelope($$parsedSource as Partial<LargeBlobMutationEnvelope>);
    }
}

export class LargeBlobReadEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: largeblobs$0.ReadReport | null;

    /** Creates a new LargeBlobReadEnvelope instance. */
    constructor($$source: Partial<LargeBlobReadEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobReadEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobReadEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType48;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new LargeBlobReadEnvelope($$parsedSource as Partial<LargeBlobReadEnvelope>);
    }
}

export class LargeBlobReadRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;
    "credentialIDHex": string;

    /** Creates a new LargeBlobReadRequest instance. */
    constructor($$source: Partial<LargeBlobReadRequest> = {}) {
        if (!("credentialIDHex" in $$source)) {
            this["credentialIDHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobReadRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobReadRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LargeBlobReadRequest($$parsedSource as Partial<LargeBlobReadRequest>);
    }
}

export class LargeBlobWriteRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;
    "credentialIDHex": string;
    "payload"?: string;
    "dryRun"?: boolean;

    /** Creates a new LargeBlobWriteRequest instance. */
    constructor($$source: Partial<LargeBlobWriteRequest> = {}) {
        if (!("credentialIDHex" in $$source)) {
            this["credentialIDHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobWriteRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobWriteRequest {
        const $$createField2_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("payload" in $$parsedSource) {
            $$parsedSource["payload"] = $$createField2_0($$parsedSource["payload"]);
        }
        return new LargeBlobWriteRequest($$parsedSource as Partial<LargeBlobWriteRequest>);
    }
}

export class LogCursor {
    "sequence": number;

    /** Creates a new LogCursor instance. */
    constructor($$source: Partial<LogCursor> = {}) {
        if (!("sequence" in $$source)) {
            this["sequence"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogCursor instance from a string or object.
     */
    static createFrom($$source: any = {}): LogCursor {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogCursor($$parsedSource as Partial<LogCursor>);
    }
}

export class MDSLookupEnvelope {
    "result": model$1.LookupResult;

    /** Creates a new MDSLookupEnvelope instance. */
    constructor($$source: Partial<MDSLookupEnvelope> = {}) {
        if (!("result" in $$source)) {
            this["result"] = (new model$1.LookupResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MDSLookupEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): MDSLookupEnvelope {
        const $$createField0_0 = $$createType49;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField0_0($$parsedSource["result"]);
        }
        return new MDSLookupEnvelope($$parsedSource as Partial<MDSLookupEnvelope>);
    }
}

export class MDSLookupRequest {
    "aaguid": string;
    "source"?: string;
    "cacheDir"?: string;
    "refresh"?: boolean;

    /** Creates a new MDSLookupRequest instance. */
    constructor($$source: Partial<MDSLookupRequest> = {}) {
        if (!("aaguid" in $$source)) {
            this["aaguid"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MDSLookupRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MDSLookupRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MDSLookupRequest($$parsedSource as Partial<MDSLookupRequest>);
    }
}

export class MakeCredentialAttestationAssessmentRequest {
    "input": webauthn$0.MakeCredentialInput;
    "result": webauthn$0.MakeCredentialResult;
    "metadata": model$1.LookupResult;

    /** Creates a new MakeCredentialAttestationAssessmentRequest instance. */
    constructor($$source: Partial<MakeCredentialAttestationAssessmentRequest> = {}) {
        if (!("input" in $$source)) {
            this["input"] = (new webauthn$0.MakeCredentialInput());
        }
        if (!("result" in $$source)) {
            this["result"] = (new webauthn$0.MakeCredentialResult());
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = (new model$1.LookupResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialAttestationAssessmentRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialAttestationAssessmentRequest {
        const $$createField0_0 = $$createType50;
        const $$createField1_0 = $$createType51;
        const $$createField2_0 = $$createType49;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("input" in $$parsedSource) {
            $$parsedSource["input"] = $$createField0_0($$parsedSource["input"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField2_0($$parsedSource["metadata"]);
        }
        return new MakeCredentialAttestationAssessmentRequest($$parsedSource as Partial<MakeCredentialAttestationAssessmentRequest>);
    }
}

export class MakeCredentialEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: webauthn$0.MakeCredentialOutput | null;

    /** Creates a new MakeCredentialEnvelope instance. */
    constructor($$source: Partial<MakeCredentialEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType53;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new MakeCredentialEnvelope($$parsedSource as Partial<MakeCredentialEnvelope>);
    }
}

export class MakeCredentialRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;
    "rp": credential$0.PublicKeyCredentialRpEntity;
    "user": credential$0.PublicKeyCredentialUserEntity;
    "clientDataJSON": string;
    "pubKeyCredParams": credential$0.PublicKeyCredentialParameters[];
    "excludeList"?: credential$0.PublicKeyCredentialDescriptor[];
    "options"?: webauthn$0.AuthenticatorOptions;
    "extensions"?: webauthn$1.CreateAuthenticationExtensionsClientInputs | null;
    "enterpriseAttestation"?: number;
    "attestationFormatsPreference"?: attestation$0.AttestationStatementFormatIdentifier[];
    "dryRun"?: boolean;

    /** Creates a new MakeCredentialRequest instance. */
    constructor($$source: Partial<MakeCredentialRequest> = {}) {
        if (!("rp" in $$source)) {
            this["rp"] = (new credential$0.PublicKeyCredentialRpEntity());
        }
        if (!("user" in $$source)) {
            this["user"] = (new credential$0.PublicKeyCredentialUserEntity());
        }
        if (!("clientDataJSON" in $$source)) {
            this["clientDataJSON"] = "";
        }
        if (!("pubKeyCredParams" in $$source)) {
            this["pubKeyCredParams"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialRequest {
        const $$createField1_0 = $$createType54;
        const $$createField2_0 = $$createType55;
        const $$createField3_0 = $Create.ByteSlice;
        const $$createField4_0 = $$createType57;
        const $$createField5_0 = $$createType30;
        const $$createField6_0 = $$createType31;
        const $$createField7_0 = $$createType59;
        const $$createField9_0 = $$createType60;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rp" in $$parsedSource) {
            $$parsedSource["rp"] = $$createField1_0($$parsedSource["rp"]);
        }
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField2_0($$parsedSource["user"]);
        }
        if ("clientDataJSON" in $$parsedSource) {
            $$parsedSource["clientDataJSON"] = $$createField3_0($$parsedSource["clientDataJSON"]);
        }
        if ("pubKeyCredParams" in $$parsedSource) {
            $$parsedSource["pubKeyCredParams"] = $$createField4_0($$parsedSource["pubKeyCredParams"]);
        }
        if ("excludeList" in $$parsedSource) {
            $$parsedSource["excludeList"] = $$createField5_0($$parsedSource["excludeList"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField6_0($$parsedSource["options"]);
        }
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField7_0($$parsedSource["extensions"]);
        }
        if ("attestationFormatsPreference" in $$parsedSource) {
            $$parsedSource["attestationFormatsPreference"] = $$createField9_0($$parsedSource["attestationFormatsPreference"]);
        }
        return new MakeCredentialRequest($$parsedSource as Partial<MakeCredentialRequest>);
    }
}

export class MakeCredentialVerificationRequest {
    "input": webauthn$0.MakeCredentialInput;
    "result": webauthn$0.MakeCredentialResult;

    /** Creates a new MakeCredentialVerificationRequest instance. */
    constructor($$source: Partial<MakeCredentialVerificationRequest> = {}) {
        if (!("input" in $$source)) {
            this["input"] = (new webauthn$0.MakeCredentialInput());
        }
        if (!("result" in $$source)) {
            this["result"] = (new webauthn$0.MakeCredentialResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialVerificationRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialVerificationRequest {
        const $$createField0_0 = $$createType50;
        const $$createField1_0 = $$createType51;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("input" in $$parsedSource) {
            $$parsedSource["input"] = $$createField0_0($$parsedSource["input"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new MakeCredentialVerificationRequest($$parsedSource as Partial<MakeCredentialVerificationRequest>);
    }
}

export class MinPINLengthRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;
    "newMinPINLength"?: number | null;
    "minPinLengthRPIDs"?: string[];
    "forceChangePin"?: boolean;
    "pinComplexityPolicy"?: boolean;
    "dryRun"?: boolean;

    /** Creates a new MinPINLengthRequest instance. */
    constructor($$source: Partial<MinPINLengthRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MinPINLengthRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): MinPINLengthRequest {
        const $$createField2_0 = $$createType61;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("minPinLengthRPIDs" in $$parsedSource) {
            $$parsedSource["minPinLengthRPIDs"] = $$createField2_0($$parsedSource["minPinLengthRPIDs"]);
        }
        return new MinPINLengthRequest($$parsedSource as Partial<MinPINLengthRequest>);
    }
}

export class OperationEventEnvelope {
    "operationId"?: OperationID;
    "selectionId": SelectionID;
    "event": model$0.OperationEvent;

    /** Creates a new OperationEventEnvelope instance. */
    constructor($$source: Partial<OperationEventEnvelope> = {}) {
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("event" in $$source)) {
            this["event"] = (new model$0.OperationEvent());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OperationEventEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): OperationEventEnvelope {
        const $$createField2_0 = $$createType62;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("event" in $$parsedSource) {
            $$parsedSource["event"] = $$createField2_0($$parsedSource["event"]);
        }
        return new OperationEventEnvelope($$parsedSource as Partial<OperationEventEnvelope>);
    }
}

export type OperationID = string;

export class OperationRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;

    /** Creates a new OperationRequest instance. */
    constructor($$source: Partial<OperationRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OperationRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): OperationRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OperationRequest($$parsedSource as Partial<OperationRequest>);
    }
}

export class PINChangeRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;

    /**
     * CurrentPIN and NewPIN participate in JSON transport. Consumers own
     * redaction at the application boundary and must not log or persist them.
     */
    "currentPIN": string;
    "newPIN": string;
    "dryRun"?: boolean;

    /** Creates a new PINChangeRequest instance. */
    constructor($$source: Partial<PINChangeRequest> = {}) {
        if (!("currentPIN" in $$source)) {
            this["currentPIN"] = "";
        }
        if (!("newPIN" in $$source)) {
            this["newPIN"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PINChangeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PINChangeRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PINChangeRequest($$parsedSource as Partial<PINChangeRequest>);
    }
}

export class PINEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: config$0.PINOutput | null;

    /** Creates a new PINEnvelope instance. */
    constructor($$source: Partial<PINEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PINEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): PINEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType64;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new PINEnvelope($$parsedSource as Partial<PINEnvelope>);
    }
}

export class PINSetRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;

    /**
     * NewPIN participates in JSON transport. Consumers own redaction at the
     * application boundary and must not log or persist serialized requests.
     */
    "newPIN": string;
    "dryRun"?: boolean;

    /** Creates a new PINSetRequest instance. */
    constructor($$source: Partial<PINSetRequest> = {}) {
        if (!("newPIN" in $$source)) {
            this["newPIN"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PINSetRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): PINSetRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PINSetRequest($$parsedSource as Partial<PINSetRequest>);
    }
}

export class ReadLogsRequest {
    "after"?: number;

    /** Creates a new ReadLogsRequest instance. */
    constructor($$source: Partial<ReadLogsRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReadLogsRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ReadLogsRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReadLogsRequest($$parsedSource as Partial<ReadLogsRequest>);
    }
}

export class ResetFactoryEnvelope {
    "operationId": OperationID;
    "selectionId": SelectionID;
    "kind": operation$0.Kind;
    "authenticatorClosed": boolean;
    "error"?: failure$0.Failure | null;
    "result"?: config$0.ResetFactoryOutput | null;

    /** Creates a new ResetFactoryEnvelope instance. */
    constructor($$source: Partial<ResetFactoryEnvelope> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("selectionId" in $$source)) {
            this["selectionId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = operation$0.Kind.$zero;
        }
        if (!("authenticatorClosed" in $$source)) {
            this["authenticatorClosed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetFactoryEnvelope instance from a string or object.
     */
    static createFrom($$source: any = {}): ResetFactoryEnvelope {
        const $$createField4_0 = $$createType1;
        const $$createField5_0 = $$createType66;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("error" in $$parsedSource) {
            $$parsedSource["error"] = $$createField4_0($$parsedSource["error"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField5_0($$parsedSource["result"]);
        }
        return new ResetFactoryEnvelope($$parsedSource as Partial<ResetFactoryEnvelope>);
    }
}

export class ResetFactoryRequest {
    "verificationFlow"?: ctapkit$0.VerificationFlow;
    "dryRun"?: boolean;

    /** Creates a new ResetFactoryRequest instance. */
    constructor($$source: Partial<ResetFactoryRequest> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResetFactoryRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ResetFactoryRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResetFactoryRequest($$parsedSource as Partial<ResetFactoryRequest>);
    }
}

export type SelectionID = string;

export class SelectionRequest {
    "attachmentId": report$0.AttachmentID;

    /** Creates a new SelectionRequest instance. */
    constructor($$source: Partial<SelectionRequest> = {}) {
        if (!("attachmentId" in $$source)) {
            this["attachmentId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectionRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SelectionRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SelectionRequest($$parsedSource as Partial<SelectionRequest>);
    }
}

// Private type creation functions
const $$createType0 = failure$0.Failure.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = config$0.AuthenticatorConfigOutput.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = report$0.DeviceReport.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ActiveSelection.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = config$0.BioEnrollOutput.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = config$0.BioListReport.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = config$0.BioMutationOutput.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = config$0.BioSensorReport.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = config$0.StatusReport.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = credentials$0.DeleteOutput.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = credentials$0.UpdateUserOutput.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
const $$createType22 = credentials$0.CredentialTarget.createFrom;
const $$createType23 = credentials$0.InventoryReport.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = webauthn$0.PreviewSignGeneratedKey.createFrom;
const $$createType26 = AuthenticatorSessionSnapshot.createFrom;
const $$createType27 = webauthn$0.GetAssertionOutput.createFrom;
const $$createType28 = $Create.Nullable($$createType27);
const $$createType29 = credential$0.PublicKeyCredentialDescriptor.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = webauthn$0.AuthenticatorOptions.createFrom;
const $$createType32 = webauthn$1.GetAuthenticationExtensionsClientInputs.createFrom;
const $$createType33 = $Create.Nullable($$createType32);
const $$createType34 = webauthn$0.GetAssertionInput.createFrom;
const $$createType35 = webauthn$0.GetAssertionResult.createFrom;
const $$createType36 = webauthn$0.CredentialVerificationMaterial.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = inspect$0.Result.createFrom;
const $$createType39 = $Create.Nullable($$createType38);
const $$createType40 = model$0.InteractionRequest.createFrom;
const $$createType41 = largeblobs$0.DecodeResult.createFrom;
const $$createType42 = $Create.Nullable($$createType41);
const $$createType43 = largeblobs$0.ListReport.createFrom;
const $$createType44 = $Create.Nullable($$createType43);
const $$createType45 = largeblobs$0.MutationOutput.createFrom;
const $$createType46 = $Create.Nullable($$createType45);
const $$createType47 = largeblobs$0.ReadReport.createFrom;
const $$createType48 = $Create.Nullable($$createType47);
const $$createType49 = model$1.LookupResult.createFrom;
const $$createType50 = webauthn$0.MakeCredentialInput.createFrom;
const $$createType51 = webauthn$0.MakeCredentialResult.createFrom;
const $$createType52 = webauthn$0.MakeCredentialOutput.createFrom;
const $$createType53 = $Create.Nullable($$createType52);
const $$createType54 = credential$0.PublicKeyCredentialRpEntity.createFrom;
const $$createType55 = credential$0.PublicKeyCredentialUserEntity.createFrom;
const $$createType56 = credential$0.PublicKeyCredentialParameters.createFrom;
const $$createType57 = $Create.Array($$createType56);
const $$createType58 = webauthn$1.CreateAuthenticationExtensionsClientInputs.createFrom;
const $$createType59 = $Create.Nullable($$createType58);
const $$createType60 = $Create.Array($Create.Any);
const $$createType61 = $Create.Array($Create.Any);
const $$createType62 = model$0.OperationEvent.createFrom;
const $$createType63 = config$0.PINOutput.createFrom;
const $$createType64 = $Create.Nullable($$createType63);
const $$createType65 = config$0.ResetFactoryOutput.createFrom;
const $$createType66 = $Create.Nullable($$createType65);
