// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$1 from "../../github.com/telesma-app/kit/model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as webauthn$0 from "../../github.com/telesma-app/kit/model/webauthn/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../../github.com/telesma-app/mds/model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AssessMakeCredentialAttestation(req: $models.MakeCredentialAttestationAssessmentRequest): $CancellablePromise<model$0.AttestationTrustAssessment> {
    return $Call.ByID(3730039850, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function BioEnroll(req: $models.BioEnrollRequest): $CancellablePromise<$models.BioEnrollEnvelope> {
    return $Call.ByID(2065051577, req).then(($result: any) => {
        return $$createType1($result);
    });
}

export function BioList(req: $models.OperationRequest): $CancellablePromise<$models.BioListEnvelope> {
    return $Call.ByID(2038348349, req).then(($result: any) => {
        return $$createType2($result);
    });
}

export function BioRemove(req: $models.BioRemoveRequest): $CancellablePromise<$models.BioMutationEnvelope> {
    return $Call.ByID(2338669921, req).then(($result: any) => {
        return $$createType3($result);
    });
}

export function BioRename(req: $models.BioRenameRequest): $CancellablePromise<$models.BioMutationEnvelope> {
    return $Call.ByID(1575637423, req).then(($result: any) => {
        return $$createType3($result);
    });
}

export function BioSensorInfo(req: $models.OperationRequest): $CancellablePromise<$models.BioSensorEnvelope> {
    return $Call.ByID(436492603, req).then(($result: any) => {
        return $$createType4($result);
    });
}

export function CancelOperation(req: $models.CancelOperationRequest): $CancellablePromise<boolean> {
    return $Call.ByID(1367638344, req);
}

export function ChangePIN(req: $models.PINChangeRequest): $CancellablePromise<$models.PINEnvelope> {
    return $Call.ByID(1144501308, req).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ClearLogs(): $CancellablePromise<$models.LogCursor> {
    return $Call.ByID(881518177).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ConfigStatus(req: $models.OperationRequest): $CancellablePromise<$models.ConfigStatusEnvelope> {
    return $Call.ByID(3362399985, req).then(($result: any) => {
        return $$createType7($result);
    });
}

export function DecodeLargeBlob(req: $models.LargeBlobDecodeRequest): $CancellablePromise<$models.LargeBlobDecodeEnvelope> {
    return $Call.ByID(2416498929, req).then(($result: any) => {
        return $$createType8($result);
    });
}

export function DeleteCredential(req: $models.CredentialDeleteRequest): $CancellablePromise<$models.CredentialDeleteEnvelope> {
    return $Call.ByID(1938314231, req).then(($result: any) => {
        return $$createType9($result);
    });
}

export function DeleteLargeBlob(req: $models.LargeBlobDeleteRequest): $CancellablePromise<$models.LargeBlobMutationEnvelope> {
    return $Call.ByID(2525871226, req).then(($result: any) => {
        return $$createType10($result);
    });
}

export function DerivePreviewSignARKGP256(req: $models.DerivePreviewSignARKGP256Request): $CancellablePromise<webauthn$0.PreviewSignARKGP256Derivation> {
    return $Call.ByID(1056837575, req).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * Discover starts device monitoring or republishes its current state. The
 * initial state and every later change are published through EventDiscoveryChanged.
 */
export function Discover(): $CancellablePromise<void> {
    return $Call.ByID(4183717870);
}

export function EnableEnterpriseAttestation(req: $models.EnableEnterpriseAttestationRequest): $CancellablePromise<$models.AuthenticatorConfigEnvelope> {
    return $Call.ByID(136034409, req).then(($result: any) => {
        return $$createType12($result);
    });
}

export function EnableLongTouchForReset(req: $models.EnableLongTouchForResetRequest): $CancellablePromise<$models.AuthenticatorConfigEnvelope> {
    return $Call.ByID(2583563405, req).then(($result: any) => {
        return $$createType12($result);
    });
}

export function GarbageCollectLargeBlobs(req: $models.LargeBlobGarbageCollectRequest): $CancellablePromise<$models.LargeBlobMutationEnvelope> {
    return $Call.ByID(3361944295, req).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetAssertion(req: $models.GetAssertionRequest): $CancellablePromise<$models.GetAssertionEnvelope> {
    return $Call.ByID(1932383177, req).then(($result: any) => {
        return $$createType13($result);
    });
}

export function Inspect(req: $models.OperationRequest): $CancellablePromise<$models.InspectEnvelope> {
    return $Call.ByID(3574876855, req).then(($result: any) => {
        return $$createType14($result);
    });
}

export function ListCredentials(req: $models.OperationRequest): $CancellablePromise<$models.CredentialsEnvelope> {
    return $Call.ByID(18371077, req).then(($result: any) => {
        return $$createType15($result);
    });
}

export function ListLargeBlobs(req: $models.OperationRequest): $CancellablePromise<$models.LargeBlobListEnvelope> {
    return $Call.ByID(2541655760, req).then(($result: any) => {
        return $$createType16($result);
    });
}

export function LookupMDS(req: $models.MDSLookupRequest): $CancellablePromise<$models.MDSLookupEnvelope> {
    return $Call.ByID(922358051, req).then(($result: any) => {
        return $$createType17($result);
    });
}

export function MakeCredential(req: $models.MakeCredentialRequest): $CancellablePromise<$models.MakeCredentialEnvelope> {
    return $Call.ByID(3527636358, req).then(($result: any) => {
        return $$createType18($result);
    });
}

export function ReadLargeBlob(req: $models.LargeBlobReadRequest): $CancellablePromise<$models.LargeBlobReadEnvelope> {
    return $Call.ByID(804278151, req).then(($result: any) => {
        return $$createType19($result);
    });
}

export function ReadLogs(req: $models.ReadLogsRequest): $CancellablePromise<model$1.LogJournalBatch> {
    return $Call.ByID(2019221894, req).then(($result: any) => {
        return $$createType20($result);
    });
}

export function ReconnectSelection(): $CancellablePromise<void> {
    return $Call.ByID(2068708288);
}

export function ResetFactory(req: $models.ResetFactoryRequest): $CancellablePromise<$models.ResetFactoryEnvelope> {
    return $Call.ByID(3099128462, req).then(($result: any) => {
        return $$createType21($result);
    });
}

export function ResolveInteraction(answer: $models.InteractionAnswer): $CancellablePromise<boolean> {
    return $Call.ByID(2161635929, answer);
}

export function SetAlwaysUV(req: $models.AlwaysUVRequest): $CancellablePromise<$models.AuthenticatorConfigEnvelope> {
    return $Call.ByID(864302713, req).then(($result: any) => {
        return $$createType12($result);
    });
}

export function SetMinPINLength(req: $models.MinPINLengthRequest): $CancellablePromise<$models.AuthenticatorConfigEnvelope> {
    return $Call.ByID(664355016, req).then(($result: any) => {
        return $$createType12($result);
    });
}

export function SetPIN(req: $models.PINSetRequest): $CancellablePromise<$models.PINEnvelope> {
    return $Call.ByID(1367512842, req).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SetSelection(req: $models.SelectionRequest): $CancellablePromise<void> {
    return $Call.ByID(3136587015, req);
}

export function UpdateCredentialUser(req: $models.CredentialUpdateRequest): $CancellablePromise<$models.CredentialUpdateEnvelope> {
    return $Call.ByID(1873826706, req).then(($result: any) => {
        return $$createType22($result);
    });
}

export function VerifyGetAssertion(req: $models.GetAssertionVerificationRequest): $CancellablePromise<webauthn$0.GetAssertionVerification> {
    return $Call.ByID(2758956860, req).then(($result: any) => {
        return $$createType23($result);
    });
}

export function VerifyMakeCredential(req: $models.MakeCredentialVerificationRequest): $CancellablePromise<webauthn$0.MakeCredentialVerification> {
    return $Call.ByID(448257851, req).then(($result: any) => {
        return $$createType24($result);
    });
}

export function WriteLargeBlob(req: $models.LargeBlobWriteRequest): $CancellablePromise<$models.LargeBlobMutationEnvelope> {
    return $Call.ByID(3705545108, req).then(($result: any) => {
        return $$createType10($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.AttestationTrustAssessment.createFrom;
const $$createType1 = $models.BioEnrollEnvelope.createFrom;
const $$createType2 = $models.BioListEnvelope.createFrom;
const $$createType3 = $models.BioMutationEnvelope.createFrom;
const $$createType4 = $models.BioSensorEnvelope.createFrom;
const $$createType5 = $models.PINEnvelope.createFrom;
const $$createType6 = $models.LogCursor.createFrom;
const $$createType7 = $models.ConfigStatusEnvelope.createFrom;
const $$createType8 = $models.LargeBlobDecodeEnvelope.createFrom;
const $$createType9 = $models.CredentialDeleteEnvelope.createFrom;
const $$createType10 = $models.LargeBlobMutationEnvelope.createFrom;
const $$createType11 = webauthn$0.PreviewSignARKGP256Derivation.createFrom;
const $$createType12 = $models.AuthenticatorConfigEnvelope.createFrom;
const $$createType13 = $models.GetAssertionEnvelope.createFrom;
const $$createType14 = $models.InspectEnvelope.createFrom;
const $$createType15 = $models.CredentialsEnvelope.createFrom;
const $$createType16 = $models.LargeBlobListEnvelope.createFrom;
const $$createType17 = $models.MDSLookupEnvelope.createFrom;
const $$createType18 = $models.MakeCredentialEnvelope.createFrom;
const $$createType19 = $models.LargeBlobReadEnvelope.createFrom;
const $$createType20 = model$1.LogJournalBatch.createFrom;
const $$createType21 = $models.ResetFactoryEnvelope.createFrom;
const $$createType22 = $models.CredentialUpdateEnvelope.createFrom;
const $$createType23 = webauthn$0.GetAssertionVerification.createFrom;
const $$createType24 = webauthn$0.MakeCredentialVerification.createFrom;
