// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as attestation$0 from "../../../ctap/attestation/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as cose$0 from "../../../ctap/cose/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as credential$0 from "../../../ctap/credential/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as extension$0 from "../../../ctap/extension/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as webauthn$0 from "../../../ctap/webauthn/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as report$0 from "../report/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as safety$0 from "../safety/models.js";

export class Assertion {
    "index": number;
    "credential": credential$0.PublicKeyCredentialDescriptor;
    "authenticatorDataHex": string;
    "signatureHex": string;
    "user"?: credential$0.PublicKeyCredentialUserEntity | null;
    "numberOfCredentials"?: number;
    "userSelected"?: boolean;
    "signCount": number;
    "userPresent": boolean;
    "userVerified": boolean;
    "extensionResults"?: GetAssertionExtensionResults | null;

    /** Creates a new Assertion instance. */
    constructor($$source: Partial<Assertion> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("credential" in $$source)) {
            this["credential"] = (new credential$0.PublicKeyCredentialDescriptor());
        }
        if (!("authenticatorDataHex" in $$source)) {
            this["authenticatorDataHex"] = "";
        }
        if (!("signatureHex" in $$source)) {
            this["signatureHex"] = "";
        }
        if (!("signCount" in $$source)) {
            this["signCount"] = 0;
        }
        if (!("userPresent" in $$source)) {
            this["userPresent"] = false;
        }
        if (!("userVerified" in $$source)) {
            this["userVerified"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Assertion instance from a string or object.
     */
    static createFrom($$source: any = {}): Assertion {
        const $$createField1_0 = $$createType0;
        const $$createField4_0 = $$createType2;
        const $$createField10_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("credential" in $$parsedSource) {
            $$parsedSource["credential"] = $$createField1_0($$parsedSource["credential"]);
        }
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField4_0($$parsedSource["user"]);
        }
        if ("extensionResults" in $$parsedSource) {
            $$parsedSource["extensionResults"] = $$createField10_0($$parsedSource["extensionResults"]);
        }
        return new Assertion($$parsedSource as Partial<Assertion>);
    }
}

export class AssertionVerification {
    "index": number;
    "credentialIDHex": string;
    "status": VerificationStatus;
    "rpIDHashMatches": boolean;
    "userPresenceRequirementMet": boolean;
    "userVerificationRequirementMet": boolean;
    "credentialAllowed": boolean;
    "signatureValid"?: boolean | null;
    "signCount": SignCountStatus;
    "issues"?: VerificationIssueCode[];
    "warnings"?: VerificationIssueCode[];

    /** Creates a new AssertionVerification instance. */
    constructor($$source: Partial<AssertionVerification> = {}) {
        if (!("index" in $$source)) {
            this["index"] = 0;
        }
        if (!("credentialIDHex" in $$source)) {
            this["credentialIDHex"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = VerificationStatus.$zero;
        }
        if (!("rpIDHashMatches" in $$source)) {
            this["rpIDHashMatches"] = false;
        }
        if (!("userPresenceRequirementMet" in $$source)) {
            this["userPresenceRequirementMet"] = false;
        }
        if (!("userVerificationRequirementMet" in $$source)) {
            this["userVerificationRequirementMet"] = false;
        }
        if (!("credentialAllowed" in $$source)) {
            this["credentialAllowed"] = false;
        }
        if (!("signCount" in $$source)) {
            this["signCount"] = SignCountStatus.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssertionVerification instance from a string or object.
     */
    static createFrom($$source: any = {}): AssertionVerification {
        const $$createField9_0 = $$createType5;
        const $$createField10_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField9_0($$parsedSource["issues"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField10_0($$parsedSource["warnings"]);
        }
        return new AssertionVerification($$parsedSource as Partial<AssertionVerification>);
    }
}

/**
 * AttestationType describes the attestation evidence verified by ctapkit.
 */
export enum AttestationType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AttestationTypeNone = "none",
    AttestationTypeSelf = "self",
    AttestationTypeBasic = "basic",
    AttestationTypeUnsupported = "unsupported",
};

export class AuthenticatorOptions {
    "residentKey"?: boolean | null;
    "userPresence"?: boolean | null;
    "userVerification"?: boolean | null;

    /** Creates a new AuthenticatorOptions instance. */
    constructor($$source: Partial<AuthenticatorOptions> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuthenticatorOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): AuthenticatorOptions {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuthenticatorOptions($$parsedSource as Partial<AuthenticatorOptions>);
    }
}

export class CredentialBlobCreateOutput {
    "accepted": boolean;

    /** Creates a new CredentialBlobCreateOutput instance. */
    constructor($$source: Partial<CredentialBlobCreateOutput> = {}) {
        if (!("accepted" in $$source)) {
            this["accepted"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialBlobCreateOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialBlobCreateOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialBlobCreateOutput($$parsedSource as Partial<CredentialBlobCreateOutput>);
    }
}

export class CredentialBlobGetOutput {
    "valueHex": string;

    /** Creates a new CredentialBlobGetOutput instance. */
    constructor($$source: Partial<CredentialBlobGetOutput> = {}) {
        if (!("valueHex" in $$source)) {
            this["valueHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialBlobGetOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialBlobGetOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialBlobGetOutput($$parsedSource as Partial<CredentialBlobGetOutput>);
    }
}

export class CredentialProtectionOutput {
    "policy": extension$0.CredentialProtectionPolicy;

    /** Creates a new CredentialProtectionOutput instance. */
    constructor($$source: Partial<CredentialProtectionOutput> = {}) {
        if (!("policy" in $$source)) {
            this["policy"] = extension$0.CredentialProtectionPolicy.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialProtectionOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialProtectionOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialProtectionOutput($$parsedSource as Partial<CredentialProtectionOutput>);
    }
}

/**
 * CredentialVerificationMaterial supplies assertion verification state owned by the application.
 */
export class CredentialVerificationMaterial {
    "credentialIDHex": string;
    "publicKeyCOSEHex": string;
    "previousSignCount"?: number | null;

    /** Creates a new CredentialVerificationMaterial instance. */
    constructor($$source: Partial<CredentialVerificationMaterial> = {}) {
        if (!("credentialIDHex" in $$source)) {
            this["credentialIDHex"] = "";
        }
        if (!("publicKeyCOSEHex" in $$source)) {
            this["publicKeyCOSEHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialVerificationMaterial instance from a string or object.
     */
    static createFrom($$source: any = {}): CredentialVerificationMaterial {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialVerificationMaterial($$parsedSource as Partial<CredentialVerificationMaterial>);
    }
}

export class GetAssertionAuthenticatorExtensionOutputs {
    "thirdPartyPayment"?: boolean | null;

    /** Creates a new GetAssertionAuthenticatorExtensionOutputs instance. */
    constructor($$source: Partial<GetAssertionAuthenticatorExtensionOutputs> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionAuthenticatorExtensionOutputs instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAssertionAuthenticatorExtensionOutputs {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetAssertionAuthenticatorExtensionOutputs($$parsedSource as Partial<GetAssertionAuthenticatorExtensionOutputs>);
    }
}

export class GetAssertionClientExtensionResults {
    "getCredBlob"?: CredentialBlobGetOutput | null;
    "hmac-secret"?: HMACSecretOutput | null;
    "prf"?: GetAssertionPRFOutput | null;
    "largeBlob"?: LargeBlobGetOutput | null;
    "previewSign"?: GetAssertionPreviewSignOutput | null;

    /** Creates a new GetAssertionClientExtensionResults instance. */
    constructor($$source: Partial<GetAssertionClientExtensionResults> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionClientExtensionResults instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAssertionClientExtensionResults {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType9;
        const $$createField2_0 = $$createType11;
        const $$createField3_0 = $$createType13;
        const $$createField4_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("getCredBlob" in $$parsedSource) {
            $$parsedSource["getCredBlob"] = $$createField0_0($$parsedSource["getCredBlob"]);
        }
        if ("hmac-secret" in $$parsedSource) {
            $$parsedSource["hmac-secret"] = $$createField1_0($$parsedSource["hmac-secret"]);
        }
        if ("prf" in $$parsedSource) {
            $$parsedSource["prf"] = $$createField2_0($$parsedSource["prf"]);
        }
        if ("largeBlob" in $$parsedSource) {
            $$parsedSource["largeBlob"] = $$createField3_0($$parsedSource["largeBlob"]);
        }
        if ("previewSign" in $$parsedSource) {
            $$parsedSource["previewSign"] = $$createField4_0($$parsedSource["previewSign"]);
        }
        return new GetAssertionClientExtensionResults($$parsedSource as Partial<GetAssertionClientExtensionResults>);
    }
}

export class GetAssertionExtensionResults {
    "client"?: GetAssertionClientExtensionResults | null;
    "authenticator"?: GetAssertionAuthenticatorExtensionOutputs | null;

    /** Creates a new GetAssertionExtensionResults instance. */
    constructor($$source: Partial<GetAssertionExtensionResults> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionExtensionResults instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAssertionExtensionResults {
        const $$createField0_0 = $$createType17;
        const $$createField1_0 = $$createType19;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("client" in $$parsedSource) {
            $$parsedSource["client"] = $$createField0_0($$parsedSource["client"]);
        }
        if ("authenticator" in $$parsedSource) {
            $$parsedSource["authenticator"] = $$createField1_0($$parsedSource["authenticator"]);
        }
        return new GetAssertionExtensionResults($$parsedSource as Partial<GetAssertionExtensionResults>);
    }
}

export class GetAssertionInput {
    "rpID": string;
    "clientDataJSON": string;
    "allowList"?: credential$0.PublicKeyCredentialDescriptor[];
    "options"?: AuthenticatorOptions;
    "extensions"?: webauthn$0.GetAuthenticationExtensionsClientInputs | null;

    /** Creates a new GetAssertionInput instance. */
    constructor($$source: Partial<GetAssertionInput> = {}) {
        if (!("rpID" in $$source)) {
            this["rpID"] = "";
        }
        if (!("clientDataJSON" in $$source)) {
            this["clientDataJSON"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAssertionInput {
        const $$createField1_0 = $Create.ByteSlice;
        const $$createField2_0 = $$createType20;
        const $$createField3_0 = $$createType21;
        const $$createField4_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("clientDataJSON" in $$parsedSource) {
            $$parsedSource["clientDataJSON"] = $$createField1_0($$parsedSource["clientDataJSON"]);
        }
        if ("allowList" in $$parsedSource) {
            $$parsedSource["allowList"] = $$createField2_0($$parsedSource["allowList"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField3_0($$parsedSource["options"]);
        }
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField4_0($$parsedSource["extensions"]);
        }
        return new GetAssertionInput($$parsedSource as Partial<GetAssertionInput>);
    }
}

export class GetAssertionOutput {
    "preview": GetAssertionPreview;
    "result": GetAssertionResult | null;

    /** Creates a new GetAssertionOutput instance. */
    constructor($$source: Partial<GetAssertionOutput> = {}) {
        if (!("preview" in $$source)) {
            this["preview"] = (new GetAssertionPreview());
        }
        if (!("result" in $$source)) {
            this["result"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAssertionOutput {
        const $$createField0_0 = $$createType24;
        const $$createField1_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField0_0($$parsedSource["preview"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new GetAssertionOutput($$parsedSource as Partial<GetAssertionOutput>);
    }
}

export class GetAssertionPRFOutput {
    "results"?: webauthn$0.AuthenticationExtensionsPRFValues;

    /** Creates a new GetAssertionPRFOutput instance. */
    constructor($$source: Partial<GetAssertionPRFOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionPRFOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAssertionPRFOutput {
        const $$createField0_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new GetAssertionPRFOutput($$parsedSource as Partial<GetAssertionPRFOutput>);
    }
}

export class GetAssertionPreview {
    "device": report$0.DeviceReport;
    "input": GetAssertionInput;
    "warnings"?: safety$0.Warning[];

    /** Creates a new GetAssertionPreview instance. */
    constructor($$source: Partial<GetAssertionPreview> = {}) {
        if (!("device" in $$source)) {
            this["device"] = (new report$0.DeviceReport());
        }
        if (!("input" in $$source)) {
            this["input"] = (new GetAssertionInput());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionPreview instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAssertionPreview {
        const $$createField0_0 = $$createType28;
        const $$createField1_0 = $$createType29;
        const $$createField2_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("device" in $$parsedSource) {
            $$parsedSource["device"] = $$createField0_0($$parsedSource["device"]);
        }
        if ("input" in $$parsedSource) {
            $$parsedSource["input"] = $$createField1_0($$parsedSource["input"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField2_0($$parsedSource["warnings"]);
        }
        return new GetAssertionPreview($$parsedSource as Partial<GetAssertionPreview>);
    }
}

export class GetAssertionPreviewSignOutput {
    "signatureHex": string;

    /** Creates a new GetAssertionPreviewSignOutput instance. */
    constructor($$source: Partial<GetAssertionPreviewSignOutput> = {}) {
        if (!("signatureHex" in $$source)) {
            this["signatureHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionPreviewSignOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAssertionPreviewSignOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GetAssertionPreviewSignOutput($$parsedSource as Partial<GetAssertionPreviewSignOutput>);
    }
}

export class GetAssertionResult {
    "attachmentId": report$0.AttachmentID;
    "rpID": string;
    "assertions"?: Assertion[];

    /** Creates a new GetAssertionResult instance. */
    constructor($$source: Partial<GetAssertionResult> = {}) {
        if (!("attachmentId" in $$source)) {
            this["attachmentId"] = "";
        }
        if (!("rpID" in $$source)) {
            this["rpID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAssertionResult {
        const $$createField2_0 = $$createType33;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assertions" in $$parsedSource) {
            $$parsedSource["assertions"] = $$createField2_0($$parsedSource["assertions"]);
        }
        return new GetAssertionResult($$parsedSource as Partial<GetAssertionResult>);
    }
}

export class GetAssertionVerification {
    "status": VerificationStatus;
    "assertions": AssertionVerification[];
    "issues"?: VerificationIssueCode[];

    /** Creates a new GetAssertionVerification instance. */
    constructor($$source: Partial<GetAssertionVerification> = {}) {
        if (!("status" in $$source)) {
            this["status"] = VerificationStatus.$zero;
        }
        if (!("assertions" in $$source)) {
            this["assertions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GetAssertionVerification instance from a string or object.
     */
    static createFrom($$source: any = {}): GetAssertionVerification {
        const $$createField1_0 = $$createType35;
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assertions" in $$parsedSource) {
            $$parsedSource["assertions"] = $$createField1_0($$parsedSource["assertions"]);
        }
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField2_0($$parsedSource["issues"]);
        }
        return new GetAssertionVerification($$parsedSource as Partial<GetAssertionVerification>);
    }
}

export class HMACSecretCreateOutput {
    "enabled": boolean;

    /** Creates a new HMACSecretCreateOutput instance. */
    constructor($$source: Partial<HMACSecretCreateOutput> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HMACSecretCreateOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): HMACSecretCreateOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HMACSecretCreateOutput($$parsedSource as Partial<HMACSecretCreateOutput>);
    }
}

export class HMACSecretOutput {
    "output1Hex": string;
    "output2Hex"?: string;

    /** Creates a new HMACSecretOutput instance. */
    constructor($$source: Partial<HMACSecretOutput> = {}) {
        if (!("output1Hex" in $$source)) {
            this["output1Hex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HMACSecretOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): HMACSecretOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HMACSecretOutput($$parsedSource as Partial<HMACSecretOutput>);
    }
}

export class LargeBlobCreateOutput {
    "supported": boolean;

    /** Creates a new LargeBlobCreateOutput instance. */
    constructor($$source: Partial<LargeBlobCreateOutput> = {}) {
        if (!("supported" in $$source)) {
            this["supported"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobCreateOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobCreateOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LargeBlobCreateOutput($$parsedSource as Partial<LargeBlobCreateOutput>);
    }
}

export class LargeBlobGetOutput {
    "blobHex"?: string | null;
    "written"?: boolean | null;

    /** Creates a new LargeBlobGetOutput instance. */
    constructor($$source: Partial<LargeBlobGetOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LargeBlobGetOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): LargeBlobGetOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LargeBlobGetOutput($$parsedSource as Partial<LargeBlobGetOutput>);
    }
}

export class MakeCredentialAuthenticatorExtensionOutputs {
    "credProtect"?: CredentialProtectionOutput | null;
    "minPinLength"?: MinPINLengthOutput | null;
    "pinComplexityPolicy"?: PINComplexityPolicyOutput | null;

    /** Creates a new MakeCredentialAuthenticatorExtensionOutputs instance. */
    constructor($$source: Partial<MakeCredentialAuthenticatorExtensionOutputs> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialAuthenticatorExtensionOutputs instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialAuthenticatorExtensionOutputs {
        const $$createField0_0 = $$createType37;
        const $$createField1_0 = $$createType39;
        const $$createField2_0 = $$createType41;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("credProtect" in $$parsedSource) {
            $$parsedSource["credProtect"] = $$createField0_0($$parsedSource["credProtect"]);
        }
        if ("minPinLength" in $$parsedSource) {
            $$parsedSource["minPinLength"] = $$createField1_0($$parsedSource["minPinLength"]);
        }
        if ("pinComplexityPolicy" in $$parsedSource) {
            $$parsedSource["pinComplexityPolicy"] = $$createField2_0($$parsedSource["pinComplexityPolicy"]);
        }
        return new MakeCredentialAuthenticatorExtensionOutputs($$parsedSource as Partial<MakeCredentialAuthenticatorExtensionOutputs>);
    }
}

export class MakeCredentialClientExtensionResults {
    "credProps"?: webauthn$0.CredentialPropertiesOutput | null;
    "credBlob"?: CredentialBlobCreateOutput | null;
    "hmac-secret"?: HMACSecretCreateOutput | null;
    "hmac-secret-mc"?: HMACSecretOutput | null;
    "prf"?: MakeCredentialPRFOutput | null;
    "largeBlob"?: LargeBlobCreateOutput | null;
    "previewSign"?: MakeCredentialPreviewSignOutput | null;

    /** Creates a new MakeCredentialClientExtensionResults instance. */
    constructor($$source: Partial<MakeCredentialClientExtensionResults> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialClientExtensionResults instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialClientExtensionResults {
        const $$createField0_0 = $$createType43;
        const $$createField1_0 = $$createType45;
        const $$createField2_0 = $$createType47;
        const $$createField3_0 = $$createType9;
        const $$createField4_0 = $$createType49;
        const $$createField5_0 = $$createType51;
        const $$createField6_0 = $$createType53;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("credProps" in $$parsedSource) {
            $$parsedSource["credProps"] = $$createField0_0($$parsedSource["credProps"]);
        }
        if ("credBlob" in $$parsedSource) {
            $$parsedSource["credBlob"] = $$createField1_0($$parsedSource["credBlob"]);
        }
        if ("hmac-secret" in $$parsedSource) {
            $$parsedSource["hmac-secret"] = $$createField2_0($$parsedSource["hmac-secret"]);
        }
        if ("hmac-secret-mc" in $$parsedSource) {
            $$parsedSource["hmac-secret-mc"] = $$createField3_0($$parsedSource["hmac-secret-mc"]);
        }
        if ("prf" in $$parsedSource) {
            $$parsedSource["prf"] = $$createField4_0($$parsedSource["prf"]);
        }
        if ("largeBlob" in $$parsedSource) {
            $$parsedSource["largeBlob"] = $$createField5_0($$parsedSource["largeBlob"]);
        }
        if ("previewSign" in $$parsedSource) {
            $$parsedSource["previewSign"] = $$createField6_0($$parsedSource["previewSign"]);
        }
        return new MakeCredentialClientExtensionResults($$parsedSource as Partial<MakeCredentialClientExtensionResults>);
    }
}

export class MakeCredentialExtensionResults {
    "client"?: MakeCredentialClientExtensionResults | null;
    "authenticator"?: MakeCredentialAuthenticatorExtensionOutputs | null;

    /** Creates a new MakeCredentialExtensionResults instance. */
    constructor($$source: Partial<MakeCredentialExtensionResults> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialExtensionResults instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialExtensionResults {
        const $$createField0_0 = $$createType55;
        const $$createField1_0 = $$createType57;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("client" in $$parsedSource) {
            $$parsedSource["client"] = $$createField0_0($$parsedSource["client"]);
        }
        if ("authenticator" in $$parsedSource) {
            $$parsedSource["authenticator"] = $$createField1_0($$parsedSource["authenticator"]);
        }
        return new MakeCredentialExtensionResults($$parsedSource as Partial<MakeCredentialExtensionResults>);
    }
}

export class MakeCredentialInput {
    "rp": credential$0.PublicKeyCredentialRpEntity;
    "user": credential$0.PublicKeyCredentialUserEntity;
    "clientDataJSON": string;
    "pubKeyCredParams": credential$0.PublicKeyCredentialParameters[];
    "excludeList"?: credential$0.PublicKeyCredentialDescriptor[];
    "options"?: AuthenticatorOptions;
    "extensions"?: webauthn$0.CreateAuthenticationExtensionsClientInputs | null;
    "enterpriseAttestation"?: number;
    "attestationFormatsPreference"?: attestation$0.AttestationStatementFormatIdentifier[];

    /** Creates a new MakeCredentialInput instance. */
    constructor($$source: Partial<MakeCredentialInput> = {}) {
        if (!("rp" in $$source)) {
            this["rp"] = (new credential$0.PublicKeyCredentialRpEntity());
        }
        if (!("user" in $$source)) {
            this["user"] = (new credential$0.PublicKeyCredentialUserEntity());
        }
        if (!("clientDataJSON" in $$source)) {
            this["clientDataJSON"] = "";
        }
        if (!("pubKeyCredParams" in $$source)) {
            this["pubKeyCredParams"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialInput instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialInput {
        const $$createField0_0 = $$createType58;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $Create.ByteSlice;
        const $$createField3_0 = $$createType60;
        const $$createField4_0 = $$createType20;
        const $$createField5_0 = $$createType21;
        const $$createField6_0 = $$createType62;
        const $$createField8_0 = $$createType63;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rp" in $$parsedSource) {
            $$parsedSource["rp"] = $$createField0_0($$parsedSource["rp"]);
        }
        if ("user" in $$parsedSource) {
            $$parsedSource["user"] = $$createField1_0($$parsedSource["user"]);
        }
        if ("clientDataJSON" in $$parsedSource) {
            $$parsedSource["clientDataJSON"] = $$createField2_0($$parsedSource["clientDataJSON"]);
        }
        if ("pubKeyCredParams" in $$parsedSource) {
            $$parsedSource["pubKeyCredParams"] = $$createField3_0($$parsedSource["pubKeyCredParams"]);
        }
        if ("excludeList" in $$parsedSource) {
            $$parsedSource["excludeList"] = $$createField4_0($$parsedSource["excludeList"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField5_0($$parsedSource["options"]);
        }
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField6_0($$parsedSource["extensions"]);
        }
        if ("attestationFormatsPreference" in $$parsedSource) {
            $$parsedSource["attestationFormatsPreference"] = $$createField8_0($$parsedSource["attestationFormatsPreference"]);
        }
        return new MakeCredentialInput($$parsedSource as Partial<MakeCredentialInput>);
    }
}

export class MakeCredentialOutput {
    "preview": MakeCredentialPreview;
    "result": MakeCredentialResult | null;

    /** Creates a new MakeCredentialOutput instance. */
    constructor($$source: Partial<MakeCredentialOutput> = {}) {
        if (!("preview" in $$source)) {
            this["preview"] = (new MakeCredentialPreview());
        }
        if (!("result" in $$source)) {
            this["result"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialOutput {
        const $$createField0_0 = $$createType64;
        const $$createField1_0 = $$createType66;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preview" in $$parsedSource) {
            $$parsedSource["preview"] = $$createField0_0($$parsedSource["preview"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new MakeCredentialOutput($$parsedSource as Partial<MakeCredentialOutput>);
    }
}

export class MakeCredentialPRFOutput {
    "enabled": boolean;
    "results"?: webauthn$0.AuthenticationExtensionsPRFValues;

    /** Creates a new MakeCredentialPRFOutput instance. */
    constructor($$source: Partial<MakeCredentialPRFOutput> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialPRFOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialPRFOutput {
        const $$createField1_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField1_0($$parsedSource["results"]);
        }
        return new MakeCredentialPRFOutput($$parsedSource as Partial<MakeCredentialPRFOutput>);
    }
}

export class MakeCredentialPreview {
    "device": report$0.DeviceReport;
    "input": MakeCredentialInput;
    "warnings"?: safety$0.Warning[];

    /** Creates a new MakeCredentialPreview instance. */
    constructor($$source: Partial<MakeCredentialPreview> = {}) {
        if (!("device" in $$source)) {
            this["device"] = (new report$0.DeviceReport());
        }
        if (!("input" in $$source)) {
            this["input"] = (new MakeCredentialInput());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialPreview instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialPreview {
        const $$createField0_0 = $$createType28;
        const $$createField1_0 = $$createType67;
        const $$createField2_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("device" in $$parsedSource) {
            $$parsedSource["device"] = $$createField0_0($$parsedSource["device"]);
        }
        if ("input" in $$parsedSource) {
            $$parsedSource["input"] = $$createField1_0($$parsedSource["input"]);
        }
        if ("warnings" in $$parsedSource) {
            $$parsedSource["warnings"] = $$createField2_0($$parsedSource["warnings"]);
        }
        return new MakeCredentialPreview($$parsedSource as Partial<MakeCredentialPreview>);
    }
}

export class MakeCredentialPreviewSignOutput {
    "generatedKey"?: PreviewSignGeneratedKey | null;

    /** Creates a new MakeCredentialPreviewSignOutput instance. */
    constructor($$source: Partial<MakeCredentialPreviewSignOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialPreviewSignOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialPreviewSignOutput {
        const $$createField0_0 = $$createType69;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("generatedKey" in $$parsedSource) {
            $$parsedSource["generatedKey"] = $$createField0_0($$parsedSource["generatedKey"]);
        }
        return new MakeCredentialPreviewSignOutput($$parsedSource as Partial<MakeCredentialPreviewSignOutput>);
    }
}

export class MakeCredentialResult {
    "attachmentId": report$0.AttachmentID;
    "rpID": string;
    "fmt": attestation$0.AttestationStatementFormatIdentifier;
    "credentialIDHex": string;
    "publicKeyCOSEHex": string;
    "authenticatorDataHex": string;
    "attestationObjectCBORHex": string;
    "aaguid"?: string;
    "signCount": number;
    "userPresent": boolean;
    "userVerified": boolean;
    "enterpriseAttestation"?: boolean;
    "extensionResults"?: MakeCredentialExtensionResults | null;

    /** Creates a new MakeCredentialResult instance. */
    constructor($$source: Partial<MakeCredentialResult> = {}) {
        if (!("attachmentId" in $$source)) {
            this["attachmentId"] = "";
        }
        if (!("rpID" in $$source)) {
            this["rpID"] = "";
        }
        if (!("fmt" in $$source)) {
            this["fmt"] = attestation$0.AttestationStatementFormatIdentifier.$zero;
        }
        if (!("credentialIDHex" in $$source)) {
            this["credentialIDHex"] = "";
        }
        if (!("publicKeyCOSEHex" in $$source)) {
            this["publicKeyCOSEHex"] = "";
        }
        if (!("authenticatorDataHex" in $$source)) {
            this["authenticatorDataHex"] = "";
        }
        if (!("attestationObjectCBORHex" in $$source)) {
            this["attestationObjectCBORHex"] = "";
        }
        if (!("signCount" in $$source)) {
            this["signCount"] = 0;
        }
        if (!("userPresent" in $$source)) {
            this["userPresent"] = false;
        }
        if (!("userVerified" in $$source)) {
            this["userVerified"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialResult {
        const $$createField12_0 = $$createType71;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensionResults" in $$parsedSource) {
            $$parsedSource["extensionResults"] = $$createField12_0($$parsedSource["extensionResults"]);
        }
        return new MakeCredentialResult($$parsedSource as Partial<MakeCredentialResult>);
    }
}

export class MakeCredentialVerification {
    "status": VerificationStatus;
    "rpIDHashMatches": boolean;
    "userPresenceRequirementMet": boolean;
    "userVerificationRequirementMet": boolean;
    "credentialAlgorithmAllowed": boolean;
    "attestationFormat": attestation$0.AttestationStatementFormatIdentifier;
    "attestationType": AttestationType;
    "signatureValid"?: boolean | null;
    "issues"?: VerificationIssueCode[];

    /** Creates a new MakeCredentialVerification instance. */
    constructor($$source: Partial<MakeCredentialVerification> = {}) {
        if (!("status" in $$source)) {
            this["status"] = VerificationStatus.$zero;
        }
        if (!("rpIDHashMatches" in $$source)) {
            this["rpIDHashMatches"] = false;
        }
        if (!("userPresenceRequirementMet" in $$source)) {
            this["userPresenceRequirementMet"] = false;
        }
        if (!("userVerificationRequirementMet" in $$source)) {
            this["userVerificationRequirementMet"] = false;
        }
        if (!("credentialAlgorithmAllowed" in $$source)) {
            this["credentialAlgorithmAllowed"] = false;
        }
        if (!("attestationFormat" in $$source)) {
            this["attestationFormat"] = attestation$0.AttestationStatementFormatIdentifier.$zero;
        }
        if (!("attestationType" in $$source)) {
            this["attestationType"] = AttestationType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MakeCredentialVerification instance from a string or object.
     */
    static createFrom($$source: any = {}): MakeCredentialVerification {
        const $$createField8_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField8_0($$parsedSource["issues"]);
        }
        return new MakeCredentialVerification($$parsedSource as Partial<MakeCredentialVerification>);
    }
}

export class MinPINLengthOutput {
    "value": number;

    /** Creates a new MinPINLengthOutput instance. */
    constructor($$source: Partial<MinPINLengthOutput> = {}) {
        if (!("value" in $$source)) {
            this["value"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MinPINLengthOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): MinPINLengthOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MinPINLengthOutput($$parsedSource as Partial<MinPINLengthOutput>);
    }
}

export class PINComplexityPolicyOutput {
    "enabled": boolean;

    /** Creates a new PINComplexityPolicyOutput instance. */
    constructor($$source: Partial<PINComplexityPolicyOutput> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PINComplexityPolicyOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): PINComplexityPolicyOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PINComplexityPolicyOutput($$parsedSource as Partial<PINComplexityPolicyOutput>);
    }
}

/**
 * PreviewSignARKGP256Derivation contains the result of deriving an ARKG-P256
 * key from a previewSign public seed. The verification key is public; the
 * additional arguments are sent back to the authenticator with the sign request.
 */
export class PreviewSignARKGP256Derivation {
    "additionalArgumentsHex": string;
    "verificationKeyCOSEHex": string;

    /** Creates a new PreviewSignARKGP256Derivation instance. */
    constructor($$source: Partial<PreviewSignARKGP256Derivation> = {}) {
        if (!("additionalArgumentsHex" in $$source)) {
            this["additionalArgumentsHex"] = "";
        }
        if (!("verificationKeyCOSEHex" in $$source)) {
            this["verificationKeyCOSEHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewSignARKGP256Derivation instance from a string or object.
     */
    static createFrom($$source: any = {}): PreviewSignARKGP256Derivation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreviewSignARKGP256Derivation($$parsedSource as Partial<PreviewSignARKGP256Derivation>);
    }
}

export class PreviewSignGeneratedKey {
    "keyHandleHex": string;
    "publicKeyCOSEHex": string;
    "algorithm": cose$0.Algorithm;
    "attestationObjectCBORHex": string;

    /** Creates a new PreviewSignGeneratedKey instance. */
    constructor($$source: Partial<PreviewSignGeneratedKey> = {}) {
        if (!("keyHandleHex" in $$source)) {
            this["keyHandleHex"] = "";
        }
        if (!("publicKeyCOSEHex" in $$source)) {
            this["publicKeyCOSEHex"] = "";
        }
        if (!("algorithm" in $$source)) {
            this["algorithm"] = cose$0.Algorithm.$zero;
        }
        if (!("attestationObjectCBORHex" in $$source)) {
            this["attestationObjectCBORHex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewSignGeneratedKey instance from a string or object.
     */
    static createFrom($$source: any = {}): PreviewSignGeneratedKey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreviewSignGeneratedKey($$parsedSource as Partial<PreviewSignGeneratedKey>);
    }
}

/**
 * SignCountStatus describes a comparison with a caller-supplied previous signature counter.
 */
export enum SignCountStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SignCountStatusNotChecked = "not_checked",
    SignCountStatusUnsupported = "unsupported",
    SignCountStatusAdvanced = "advanced",
    SignCountStatusNotAdvanced = "not_advanced",
};

/**
 * VerificationIssueCode identifies a compact, stable reason for a verification outcome.
 */
export enum VerificationIssueCode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    VerificationIssueResultMalformed = "webauthn.verification.result_malformed",
    VerificationIssueResultMismatch = "webauthn.verification.result_mismatch",
    VerificationIssueResultRPIDMismatch = "webauthn.verification.result_rp_id_mismatch",
    VerificationIssueAuthenticatorDataMalformed = "webauthn.verification.authenticator_data_malformed",
    VerificationIssueRPIDHashMismatch = "webauthn.verification.rp_id_hash_mismatch",
    VerificationIssueUserPresenceMissing = "webauthn.verification.user_presence_missing",
    VerificationIssueUserVerificationMissing = "webauthn.verification.user_verification_missing",
    VerificationIssueAttestedCredentialDataMissing = "webauthn.verification.attested_credential_data_missing",
    VerificationIssueAttestedCredentialDataUnexpected = "webauthn.verification.attested_credential_data_unexpected",
    VerificationIssueCredentialAlgorithmDisallowed = "webauthn.verification.credential_algorithm_disallowed",
    VerificationIssueCredentialAlgorithmUnsupported = "webauthn.verification.credential_algorithm_unsupported",
    VerificationIssueCredentialKeyMalformed = "webauthn.verification.credential_key_malformed",
    VerificationIssueCredentialDisallowed = "webauthn.verification.credential_disallowed",
    VerificationIssueAttestationObjectMalformed = "webauthn.verification.attestation_object_malformed",
    VerificationIssueAttestationObjectMismatch = "webauthn.verification.attestation_object_mismatch",
    VerificationIssueAttestationStatementMalformed = "webauthn.verification.attestation_statement_malformed",
    VerificationIssueAttestationFormatUnsupported = "webauthn.verification.attestation_format_unsupported",
    VerificationIssueAttestationSignatureInvalid = "webauthn.verification.attestation_signature_invalid",
    VerificationIssueAssertionMissing = "webauthn.verification.assertion_missing",
    VerificationIssueAssertionCountUnexpected = "webauthn.verification.assertion_count_unexpected",
    VerificationIssueVerificationMaterialMissing = "webauthn.verification.verification_material_missing",
    VerificationIssueVerificationMaterialAmbiguous = "webauthn.verification.verification_material_ambiguous",
    VerificationIssueVerificationKeyMalformed = "webauthn.verification.verification_key_malformed",
    VerificationIssueSignatureMalformed = "webauthn.verification.signature_malformed",
    VerificationIssueAssertionSignatureInvalid = "webauthn.verification.assertion_signature_invalid",
    VerificationWarningSignCountNotAdvanced = "webauthn.verification.sign_count_not_advanced",
};

/**
 * VerificationStatus is the local integrity outcome of a WebAuthn operation result.
 */
export enum VerificationStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    VerificationStatusVerified = "verified",
    VerificationStatusFailed = "failed",
    VerificationStatusUnavailable = "unavailable",
};

// Private type creation functions
const $$createType0 = credential$0.PublicKeyCredentialDescriptor.createFrom;
const $$createType1 = credential$0.PublicKeyCredentialUserEntity.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = GetAssertionExtensionResults.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = CredentialBlobGetOutput.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = HMACSecretOutput.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = GetAssertionPRFOutput.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = LargeBlobGetOutput.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = GetAssertionPreviewSignOutput.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = GetAssertionClientExtensionResults.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = GetAssertionAuthenticatorExtensionOutputs.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = $Create.Array($$createType0);
const $$createType21 = AuthenticatorOptions.createFrom;
const $$createType22 = webauthn$0.GetAuthenticationExtensionsClientInputs.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = GetAssertionPreview.createFrom;
const $$createType25 = GetAssertionResult.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = webauthn$0.AuthenticationExtensionsPRFValues.createFrom;
const $$createType28 = report$0.DeviceReport.createFrom;
const $$createType29 = GetAssertionInput.createFrom;
const $$createType30 = safety$0.Warning.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = Assertion.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = AssertionVerification.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = CredentialProtectionOutput.createFrom;
const $$createType37 = $Create.Nullable($$createType36);
const $$createType38 = MinPINLengthOutput.createFrom;
const $$createType39 = $Create.Nullable($$createType38);
const $$createType40 = PINComplexityPolicyOutput.createFrom;
const $$createType41 = $Create.Nullable($$createType40);
const $$createType42 = webauthn$0.CredentialPropertiesOutput.createFrom;
const $$createType43 = $Create.Nullable($$createType42);
const $$createType44 = CredentialBlobCreateOutput.createFrom;
const $$createType45 = $Create.Nullable($$createType44);
const $$createType46 = HMACSecretCreateOutput.createFrom;
const $$createType47 = $Create.Nullable($$createType46);
const $$createType48 = MakeCredentialPRFOutput.createFrom;
const $$createType49 = $Create.Nullable($$createType48);
const $$createType50 = LargeBlobCreateOutput.createFrom;
const $$createType51 = $Create.Nullable($$createType50);
const $$createType52 = MakeCredentialPreviewSignOutput.createFrom;
const $$createType53 = $Create.Nullable($$createType52);
const $$createType54 = MakeCredentialClientExtensionResults.createFrom;
const $$createType55 = $Create.Nullable($$createType54);
const $$createType56 = MakeCredentialAuthenticatorExtensionOutputs.createFrom;
const $$createType57 = $Create.Nullable($$createType56);
const $$createType58 = credential$0.PublicKeyCredentialRpEntity.createFrom;
const $$createType59 = credential$0.PublicKeyCredentialParameters.createFrom;
const $$createType60 = $Create.Array($$createType59);
const $$createType61 = webauthn$0.CreateAuthenticationExtensionsClientInputs.createFrom;
const $$createType62 = $Create.Nullable($$createType61);
const $$createType63 = $Create.Array($Create.Any);
const $$createType64 = MakeCredentialPreview.createFrom;
const $$createType65 = MakeCredentialResult.createFrom;
const $$createType66 = $Create.Nullable($$createType65);
const $$createType67 = MakeCredentialInput.createFrom;
const $$createType68 = PreviewSignGeneratedKey.createFrom;
const $$createType69 = $Create.Nullable($$createType68);
const $$createType70 = MakeCredentialExtensionResults.createFrom;
const $$createType71 = $Create.Nullable($$createType70);
